Why it's Bitcoin and not Blockchain
===================================

As with every new technology, in the early stages everyone likes to play Buzzword-Bingo to hype up a project. This was true for the Internet with "eCommerce" & "Social Networks", it's true for "Artificial Intelligence" & "Machine Learning", same for the "Internet of Things" and "Machine2Machine Communication" and most definitely this is the case in Bitcoin with *blockchain* and "Decentralization". Of course, all those technologies are super interesting and important, but we have to be very careful what they actually can and cannot do. Let's not get too excited about the next Pets.com that will revolutionize eCommerce...

 

First of all, why is Bitcoin so important: It is the first digital currency since 1982 that actually works! And that is already enough to celebrate, because the problem of creating artificial scarcity in a non-scarce network such as the internet is a seemingly impossible task.footnote:[Byzantine Generals Problem, introduced in 1982 by Lamport, Shostak and Pease: https://people.eecs.berkeley.edu/~luca/cs174/byzantine.pdf]

The important question is how Bitcoin creates this non-tangible scarcity? Well, it's complicated. Bitcoin requires a holistic symbiosis of several cutting edge fields, such as cryptography, decentralized network topology, open source development, game theory, incentive structure, [austrian] economics and monetary theory. Bitcoin ONLY works, because of the unique circumstances of it's creation and the combination of all those vital theories. *Blockchain* is only a very inefficient data structure that timestamps the transactions. It is only one very small part in the entire Bitcoin network and not a "cure it all" for every problem we have in the incumbent financial system. Most problems can be fixed with a general software upgrade, no *blockchain* required.

The system only works for example, when the miners who provide security, are incentivised by an INTRINSIC token, such as Bitcoin, to not destroy the system. As soon as an external physical object is managed in the *blockchain*, the entire game theory falls apart. So far, all those diamonds, real estate and cars on the blockchain have many very simple flaws: what happens if I loose my digital password [private key] to my non-digital good? Do I get locked out of my house? Can I no longer use my car? But who owns it then? Does the physical object have to be destroyed? And what if a physical thief steals my diamonds, but I still hold the digital record in my *blockchain*? Does it do me any good, will it help me get my diamonds back? Further, who enters the diamonds into the *blockchain* and why can we trust him to do a good job? What if that person makes a "mistake" and gives himself the keys to all those diamonds?

I think that all those questions are not yet answered. I'm not saying that the problem is impossible to solve, especially in an open source and free market such as digital currencies. Let us not underestimate the power of openness and shared ideas with permissionless innovation! All I'm saying is, that 100% of todays *blockchain* hype is just that: hype. There is not one single think tank that actually has even one prototype, let a lone a working product.

 

As of today, the one single use case for a *blockchain* is Bitcoin: a peer-to-peer electronic cash system. There is so much wisdom in the title of the Bitcoin white paper, let's go through it one by one:

- Peer-to-Peer means a direct transfer of ownership, from Alice to Bob without any middleman or additional settlement layers. It is atomic, either Alice sends money to Bob, or not. A transaction can not be stuck in the middle between the two. Alice thus gives up her ownership rights, and transfers the private property directly to Bob. No other party is involved in this free and voluntary exchange.

- Electronic means of course digital. So far, all digital goods are non-scarce, that means that if Alice sends Bob a pdf document, she only sends a copy, but still retains full "ownership" over the "original". Because the digital good can be copied ad infinitum with basically no costs, there is no need for ownership rights [private property] to manage who controls what. If somebody wants to have the good, Alice can send it at no cost. Therefore, no property rights apply, and thus no free exchange can occur. Therefore no prices will arise for such non-scarce goods. Thus, there is no need to allocate the resource in an efficient way, because it is unlimited in quantity. This is fantastic for information - we can all share, copy, improve, adapt and advance our combined knowledge at no cost. This sucks for a money though! A money first and foremost must be scarce. That is if Alice gives Bob a gold coin, she no longer has any ownership and control over that coin. At any one time, only one individual can have full ownership and control over such a scarce good, therefore there is the need for property rights to manage who can control what. Because of private property, individuals can engage in free exchange, which will give rise to prices. Those prices can be used by entrepreneurs to allocate all those scarce resources to their most needed task. Scarce goods are thus the only goods, that give rise to property rights, free exchange, prices and therefore resource allocation. Only a scarce good can be a money. Bitcoin is the FIRST non-tangible [i.e. digital] but scarce good! Bitcoin is the money of and for the internet. A scarce good that has all of the advantages of a digital [non-tangible] one. I should add that scarcity has nothing to do with rarity. A rare good is limited in it's quantity, but can be both scarce [gold] or non-scarce [art by one artist]; and a plentiful good can also be scarce [dirt] and non-scarce [music].

- Cash is defined as the base money, the gold coin in the hands of Alice as a private individual. It is THE money in an economy. Alice can however take her gold coin and bring it to the bank of Bob, so that Bob will physically secure her base money. Bob will hand Alice a money certificate, which gives her the right to retain the base money at any time. This certificate is a money substitute and can still be used in every day commerce. But it is NOT the cash = base money in the economy, that is only physical gold. Bitcoin is THE money in the Bitcoin economy, no other token or certificate exists, it is just Bitcoin, the base money. But also in Bitcoin, Alice can put her Bitcoin in a centralized exchange and receive a token certificate, but that token is NOT cash, it is NOT base money, it is NOT Bitcoin. [We have often seen how money substitutes can be used in fraud, e.g. Mt.Gox or Binance]

 

You might have different definitions of those terms, but those are the definitions used by Satoshi when he wrote the white paper.

Again, I'm not saying, that money will be the one and only application that a decentralized *blockchain* can be used for. Permissionless innovation will always surprise us with solutions to previously impossible problems. But what I am saying, is that *blockchain* is simply put a very very very inefficient, slow and boring database, that was first invented in the 1990s. It is only one of the many tools used to secure the intrinsic Bitcoin token in this electronic peer-to-peer cash system.

If you want to make a product that is centrally controlled, handles extrinsic value and is not money, there are countless other more efficient data structures that you can use. Not everything has to be put on a *blockchain*, it doesn't solve many problems, but rather it creates countless frictions and introduces a big cost. In Bitcoin, those costs and inefficiencies are justified, because it is the one and only censorship resistant, decentralized and politically neutral money that we have so far seen.

Let's see where freedom and competition in money will take us though, it is going to be a fun ride!
