Evolution and Attributes of Money
=================================

Why has society always used a money as an integral part of their economic structure and everyday life? Is money useful or wasteful, is it nourishing or destructive? Throughout history, several different goods have been used as a money, so when speaking of money, one must not constrain the thinking to present day currencies such as the US Dollar, Euro or Yen. Stones, feathers, shells, gems, pearls, gold and many items more have been used by civilizations as a money.footnote:[Saifedean Ammous. “2. Primitive Money, 3. Monetary Metals, 4. Government Money”, The Bitcoin Standard]footnote:[Nick Szabo 2002, Shelling Out: The Origins of Money] What is of interest in this chapter are the fundamental origins of money and why it is being used freely and willingly. Further, the specific attributes that make a good suitable for being used as a money.

In the hypothetical construct of a small and separate economy of the lonely island, Alice specializes in fishing, and bob in picking berries. If Alice prefers eighty berries over one fish and Bob values one fish higher than eighty berries, they will likely engage in a mutually beneficial trade to increase both of their individual valuation. However, this direct exchange is very limited due to the double coincidence of wantsfootnote:[Ludwig von Mieses. “1. Media of Exchange and Money” Chapter XVII. Indirect Exchange, Human Action] problem: In order for Alice and Bob to trade, each of them has to possess a good that the other person values higher than their own. However, if Alice values her good higher than Bobs proposed transaction good, she is going to trade willingly. Therefore, if Bob wants to acquire Alice’s good, he needs to find a good that she values higher than her own, for example wood. Bob can either produce this wood himself, which requires employing capital over time, or he can seek an individual that has already accumulated capital and specializes in producing wood.

Charlie lives on the island and is a specialized lumber jack and due to his accumulated capital and experience he can produce ten logs of wood per hour. Charlie values Bob’s eighty berries higher than five of his wood logs. Bob does not want to consume the wood logs himself, e.g. to build a cabin, he ultimately wants to consume Alice’s fish. But because Alice is willing to trade her fish for wood, Bob can purchase the wood from Charlie, to later exchange it for Alice’s fish. The wood is for Bob neither a production nor a consumption good, but rather a medium of exchange,footnote:[Murray N. Rothbard. “2. The Emergence of Indirect Exchange” Chapter 2. The Pattern of indirect exchange, Man, Economy and State] which he only values in the present in order to later have a liquid and available good to exchange with and acquire either a production or consumption good. It is evident in every market, that the purchasing price of any good is higher than the selling price of such good after the purchase. The smaller this discrepancy the higher the saleableness of the good.footnote:[Carl Menger. “4. Commodities as More or Less Saleable”, On the Origins of Money] To preserve the purchasing power, it is beneficial to use a medium of exchange with the highest saleability.

The emergence of a money is a process over a long period of time, and is proceeding in several steps.footnote:[Murad Mahmudov, July 2018 Monetary Evolution of Bitoin] We will discuss specifically the evolution of Bitcoin as an emerging money in detail.

First, in order for a money to be useful, it has to be exchanged for other goods, where Alice relinquishes control over her money, and Bob gives up the possession of his berries. This aspect of *scarcity* footnote:[See chpater on scarcity] is essential for a functioning money, as a non-scarce good can be multiplied and shared, so that Alice would retain a copy of that money. A money is a tool for the exchange of property rights over a scarce good, and these property rights do not apply to non-scarce goods. Thus, for any money to exist, it first must be a scarce good. The information transmitted on the internet is a non-scarce good, and it is very remarkable, that the Nakamoto Consensus in Bitcoin, morphs this information in such a way, that a scarce good emerges. As Alice is signing the Bitcoin transaction, she has advanced the chain of keys that represent the UTXO so that it is now pointing to the public address of Bob, and only with control over Bob’s private key, can this output be ever spend again. Assuming sufficient fees paid and overall valid transaction, this transferal of control is confirmed with accumulated PoW on the Bitcoin blockchain.  and  Alice has fully relinquished control and ownership over her scarce bitcoin. Bitcoin has proven this scarcity since the first block, with the assigning of control of 50 bitcoin to Satoshis keys in the coinbase transaction mining reward,footnote:[See genesis block hash 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f] and especially with the first transferal of control of 10 bitcoin from Satoshi to Hall Finney.footnote:[See block 170 with transaction id f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16]

If Alice can take back the good, after giving it to Bob, then she has reversed the trade and broken the private contract that she has initially voluntarily agreed to. She has received Bob’s good in exchange for her good, but can reclaim her good after the exchange, acquiring both goods at the expense of Bob. Thus, the attribute of scarcity must not only be uphold for one period in time, but continuously and reliably, even with malicious actors. In Bitcoin, one UTXO must only be used once, and not be *double spent*, so to prevent the creation of counterfeit currency and inflation of the money supply.footnote[see chapter on inflation]. Nakamoto Consensus declares a time ordering of transactions in blocks that hash to a value below a certain difficulty target. In order to find these blocks with a valid hash, electricity has to be expanded on computer hardware so to calculate the hash of the block and adjusting a nonce until the target is met. Once a valid block is found, it can be assumed that the miner proposing the order of transactions, has expanded energy and work to do so. Each block refers to the previous block, thus creating a chain of accumulated PoW and in order to rewrite this chain, hash calculations have to be performed. It is computationally exponentially more expansive to reorganize the chain of blocks, with increasing percentage of honest miners. With an assumption of 50% non-malicious miners, the chain with the most accumulated PoW is considered to be the one valid chain containing the true transaction history.

Alice and Bob have unique individual preferences which they will strive to satisfy. They will seek to accumulate scarce goods in order to remove this uneasiness of desire. This can be salt for seasoning, lumber for burning a fire or any other scarce good which has some everyday use case. With the genesis block and the first 50 bitcoin issued in the coinbase reward, Satoshi received the first amount of scarce bitcoin. Ever since then, a new block issues the next set of fresh UTXOs to the database, thus increasing the supply of the good so that more people can accumulate this *digital scarce collectible* footnote:[Nick Szabo, Shelling Point] by expanding work. Alice and Bob assign some value to bitcoin, in their individual preference scale. 

A good is *durable* when its essence does not perish and decay across time. The quality of the good needs to be stable over time. For example a banana has a stable freshness and value in the short term, but after a week, the banana will have rotten and therefore decreased in its value. The purchasing power of a non durable good such as a banana therefore decreases drastically over time, making it a less useful SoV. A durable good such as gold does not decay or rust over time, once it is extracted and refined, the intrinsic value does not decrease, thus the purchasing power should be more stable, making it a good money. In the Bitcoin protocol, the currency bitcoin is only a unit of account on a decentralized and immutable ledger. One bitcoin is in the present and will be in the future always defined as one Bitcoin, just as one kilogram is today and tomorrow defined as one kilogram. One Bitcoin does not over time decay to 0.99 Bitcoin. Further, so far Bitcoin has not changed its inflation schedule, making the percentage allocation of 1 bitcoin to the total supply very reliable and stable.footnote:[see chapter on inflation and money supply] Bitcoin is thus a highly durable digital good very suitable as a money.

The economy is essentially a *network of peers* interacting and exchanging scarce goods. As additional trading partners enter the market place, more specialization and diversity is introduced, and more possible trading partners are available. When Alice and Bob can only trade between them selves, they are limited to the goods and services produced by only two individuals, apples and berries. When Charlie enters the economy and produces cake, there are new trading pairs for both Alice and Bob. With each further entrepreneur joining the network, the number of possible trades is squared.footnote:[Metcalfs Law] Hal Finny installed a full node on January 10th and connected to the node operated by Satoshi. Soon after, Satoshi send Hal the first transaction of 10 bitcoin, proofing the estabilshment of the network. On the technical level, as additional fully validating nodes enter the bitcoin network, the resiliency of the peer to peer topology is increased, similar to protocols like TCP/IP, Tor or Bittorrent. This economic and technical network effect is combined to exponentially increase the value of Bitcoin with every additional peer joining the system. When Alice and Bob are holding on to bitcoin as a collectible, they are speculating that eventually, others will join the network so that it increases in utility and value. Bitcoin is inherently an inclusive system that lowers the barrier to entry for new entrepreneurs and it relies on the expansion of this economy to expand the network. The increase of possible trading partners is the initial speculation, out of this increased utility, the collectible gains in monetary value, thus price speculation logically follows. 

As the network continues to increase, so does its *antifragility*. The ecosystem has a convex response to a stressor or source of harm leading to a positive sensitivity to increase in volatility.footnote:[Nassim Taleb, Antifragility] The network gets stronger as inside and outside harms are introduced. These problems are recognized, analyzed and fixed in a decentralized approach with action pushed to the edges of the network. Bitcoin has experience several shocks, be it bugs, DoS attacks, malicious actors, speculative attacks, spam or many other stresses. However, it appears that with every harm, the immune systemfootnote:[Antonopolous, The Sewer Rat and the Bubble Boy] of Bitcoin is increased as the bugs are fixed, malicious actors rage quit, and spam reduces. Now ten years since the release of the genesis block, the network has an uptime of 99.983% with out any break in consensus rules. This hyper resiliency is one part why individuals trust Bitcoin to store and transfer immense value over this network. “The Lindy effect is the concept that the future life expectancy of a technology is in proportion to its current age.”footnote:[Willem Van Den Bergh, On Schelling points, network effects and Lindy: Inherent properties of communication, June 2018]

*Education* plays a tremendous role in this early stage of a money, as the status quo and convenience of existing system needs to be overcome. The barrier to exit are especially high for a network good, such as a money. If all the peers are on the network A, they will likely stay there and not move to network B, which has no shelling point, network or Lindy effect. The resistance to adopt new forms of money is evident in history with long transition periods of gold coins, paper notes, debt certificates, credit cards and online banking. Educating everybody about the superior attributes of a new money is a long lasting process as this information and software has to spread throughout the globe so that individuals can verify the quality of the network. Only when understanding of the subject is reached, will individuals act and enter the market place. Due to the decentralized organization of Bitcoin, there is no educational and marketing department. Individual volunteers share their information freely, including the open source software, user guides and overall education of the technology. Bitcoin grants open access and permission less innovation to anyone, and the community has provided a plethora of information, access to mailing lists, discussion groups and meetups. The information is out there, now individuals can seek to understand and act upon it.

As new entrepreneurs enter the economy, they introduce their own skills and goods they have produced. These individuals sell their goods and services in exchange for the money, thus everyone who holds this money, will gain access to these new products. This will increase the over all utility of the money, thus pushing up the demand for holding the monetary unity. As the money is being traded across the economy and individuals are buying and selling the money, the *liquidity* should increase and thus the price volatility should decrease. One single market actor will have a thinner percentage of market depth, that he will not affect the overall market price very much. This is demonstrated in Bitcoin, as throughout the early days, the network was small and thus the liquidity very low. Individual actors could manipulate the price easily with trading botsfootnote:[see MtGox Willy Bot] or whales placing huge market orders.footnote:[Lawyer of Mark Karpelés selling 30 thousand? Bitcoin at once Early 2018?] Though over time, order book depth and liquidity is increasing, and the bitcoin to usd price volatility has decreased steadily.footnote:[see chart volatility]

A money is used in many transactions per day that are separated in time and space, thus it is preferable to have a portable good which can be *transported* on person easily and cheaply. In the physical world, stones and even gold are a hassle to transport in big quantities and over long distances, therefore paper money substitutes have been historically used to represent a specified amount of gold on paper. Due to recent communication technology advancements it is now possible to send information instantly all over the globe, making the record keeping of digital money fast and widespread. The base monetary asset is bitcoin with a total supply of 21 million and with every transaction a amount is specified in the n_value field of a transaction, denominated in Satoshis. This number field is thus the amount of money being transferred in the chain of digital signatures leading to the most recent unspent transaction output. However, only when the Bitcoin script is fulfilled as being true, is the transaction considered to be valid. This script is thus a claim on the money and although the scripting language is not Turing complete, it can express a wide variety of conditions. The most common claim on money is a regular single signature script where in order to transfer the funds only one digital signature has to be added to the transaction. Other scripts are multires signature which require m out of n signatories in order to be valid. There are other OP codes for time delays such as n lock time or check sequence verify which make a transaction valid only after a certain period of time. These and several other OP codes can be strong together in complex smart contracts such as the lightning network or side chains.footnote:[see chapter on layers and reserves] All these are claims on money, cryptographically verifiable and irreversible. As the transaction is propagated to the network, nodes check if the redeem script is valid and when sufficient fee is paid, miners include the transaction in their candidate block and accumulate proof of work. Once the valid block is mined and confirmed by following blocks, the transaction is considered final and irreversible.

The prices of all the goods in the economy will differ between each good, a house is vastly more expensive than a loaf of bread. In order to facilitate this trade, the money must be divisible. *Divisibility* of a good is defined as the possibility to easily and conveniently divide or cut a good into separate pieces, without drastically decreasing its value. A sentient being such as a cow is not divisible, as you cut the cow in half, you kill it and the two halves of the cow together are not as valuable as the whole cow alive and productive. Metals such as gold can be easily melted and recast into any size or shape required and due to golds homogeneity the intrinsic value of gold is equal in dust, coins or bars. However, the cost of melting and recasting gold has to be considered when valuing the divisibility of gold, it is more costly to mint a coin than to melt it down.footnote:[Murray N. Rothbard. “6. The Shape of Money” Chapter 2: Money in a Free Society. What has Government Done to Our Money] Because of its inherent digital nature, Bitcoin is divisible up to the eighth digit, 1/100.000.000 or 0,00000001 Bitcoin is defined as one Satoshi, the smallest denomination currently accepted on the base layer chain. This lower limit can be changed if overall consensus is reached, for example sub Satoshi payments on the Lightning Network. The amount of Bitcoin send in a transaction has no impact whatsoever on its cost, the fee is equal for a transaction of one Satoshi or of one thousand Bitcoin. The digital size in bytes of the transaction is what determines the transaction fees, not the transacted value.footnote:[More on the calculation of the transaction fees at www.en.bitcoin.it/wiki/transaction_fees] All the way from a micro- up to a giga transaction, the bitcoin blockchain handles the transaction of equal regard. Though a complex multi signature or any other smart contract that requires additional block space, is charged with additional mining fees. These fees are a direct payment for network security, subsidized by coin base inflation.footnote:[see chapter on inflation and money supply]

The degree of *censorship resistance* depends on the possibility of the forceful hindrance of the individuals desired use of his property by a third party. Censorship is by definition only beneficial to the aggressor, and unbeneficial to the victim. The aggressor breaks the fundamental natural right to ownership of the body and property, thus censorship is both economically unfavorable and immoral.footnote:[see chapter types of intervention] If the individual has full control over his own property and nobody can stop his peaceful and righteous use thereof, the good is censorship resistant. For example, if the individual has full ownership of the physical gold coin, a third party can only hinder his usage by forcefully stopping his action in person, for example a thug stealing the gold coin at gunpoint. If the individual gives away partial control by depositing his gold coins into a bank vault, the bank can forcefully prohibit the access to the coins. The rouge bank does not have to forcefully take the good first, because it already was given access previously, therefore censorship resistance is decreased.
As seen in the Greek monetary crisis, a centralized digital currency such as the Euro is highly susceptible to censorship, as the bank accounts of millions of Greeks was shut down temporarily, no transfer of value was possible and the access to cash or credit card was denied. Furthermore, a centralized custodian system can always exclude individuals from using the services. Many billion people worldwide have no access to the global banking and capital markets as it is in Europe or the USA.footnote:[Chaia, Goland, Schiff for McKinsey. Half the World is Unbanked. in Journal of Banking and Finance 2008] This censorship is the partial result of the fundamental broken and immoral know your customer (KYC) and anti money laundering (AML) regulation that hinders the free entrance into the currency market and banking services.footnote:[Refer to Chapter on KYC&AML]
In Bitcoin, all that is needed to transfer control over a bitcoin is a valid signature and a transaction that has sufficient fees. As soon as this is broadcaster to the network, the transaction will eventually be added to the block chain and regarded as valid. It doesn’t matter who signed and published the transaction, if this was done by a human voluntarily or at gunpoint, or by a script or automated device. As soon as the transaction is photographically signed, it is a valid and as long as 51% of miners are honest, the longest chain will eventually include it. The cost for censoring, or for reorganizing the chain which contains the unwanted transaction, is rather large.footnote:[see chapter on mining] The transaction can be broadcaster over the gossiping protocol of full nodes, via the Tor network, satellite communication mesh networks or carrier pigeon.  Any transfer of this small piece of information to a miner is sufficient in order to gain the attention and inclusion of the transaction. The fee incentive structure of the protocol have caused that no Bitcoin transaction has ever been censored or not included in the chain.

The MoE is not directly used in the present, but rather in an uncertain future exchange. It is important, that the good does not lose too much of its value during that storing period. If the good has a high value today, but less in the future, the purchasing power is decreased, thus it hinders prosperity. If Bob picks his berries today, but plans on trading with them in the distant future, the berries will be rotten. Rotten berries are of course not as valuable than fresh berries, thus they do not store their value effectively. Bob has lost much of his wealth because he choose a non-durable good to store his wealth. But even with a durable good, that does not decay over time, if the demand for the good is lower in the future, the exchange value will decrease. If Charlie stores his wealth in wood, thinking that Alice will want to build a cabin soon, but it turns out that Alice does not want to do this, she will not demand wood in exchange, thus the value of Charlie’s wood will decrease. The better the good can retain its purchasing power, the more suitable it is as a *store of value*.

In this simplified barter economy, there is no universal price of any good. One unit of Alice’s fish will have several different ‘prices’: the ‘berry price’ in terms of Bob’s berries and the ‘wood price’ in terms of Charlie’s wood. In a more complex barter economy, every good has a quasi-infinite array of prices in terms of every other good. Each seller has to price his goods in many different goods and keep track on all the exchange values for each and every good. This is of course very cumbersome and costly, deep production stages are very hard to calculate. Because of the limited possible trades and the expensive and recurring adjustments of prices, this is a state of uneasiness which will be relieved in a free market. As more and more people use the same MoE and SoV in their transactions, the value of that good further increases, thus incentivizing more participants to use it. The more the same good is used in exchange, the more goods are priced in terms of that one good. Thus there is a natural tendency towards one single *unit of account* in which all goods are being priced. This opens up the possibility of fast and interconnected production stages in a complex economy.

That good, which is the most common medium of exchange, store of value and unit of account in the economy, is called a money. Of course, every good can be money, but that good which is the most saleable will tend to be the single money. Due to the network effect, the saleability of the money increases exponentially with each new participant in the money economy. Thus there is a natural tendency towards one single money on the free and voluntary market. This must not be confused with government legal tender laws, which force market participants to use one single money. This monopoly decreases the overall wealth and prosperity of the society. 

"But the expected value will be the decisive factor determining ho much of it the public will with to hold, and the issuing bank will soon discover that the desire of the public to hold its currency will be the essential circumstance on which its value depends. [...] The crucial point it must keep in mind will be that to keep a large and growing amount of its currency in circulation, it will be not the demand for borrowing it but the willingness of the public to hold it that will be decisive."footnote:[Hayek, The Denationalizaion of Money]

"Why do people keep any cash balances at all? Suppose that all of us were able to foretell the future with absolute certainty. In that case, no one would have to keep cash balances on hand. Everyone would know exactly how much he will spend, and how much income he will receive, at all future dates. He need not keep any money at hand, but will lend out his gold so as to receive his payments in the needed amounts on the very days he makes his expenditures. But, of course, we necessarily live in a world of uncertainty. People do 
not precisely know what will happen to them, or what their future incomes or costs will be. The more uncertain and fearful they are, the more cash balances they will want to hold; the more secure, the less cash they will wish to keep on hand. Another reason for keeping cash is also a function of the real world of uncertainty. If people expect the price of money to fall in the near future, they will spend their money now while money is more valuable, thus “dishoarding” and reducing their demand for money. Conversely, if they expect the price of money to rise, they will wait to spend money later when it is more valuable, and their demand for cash will increase. People’s demands for cash balances, then, rise and fall for good and sound reasons."footnote:[Rothbard, What has government done to our money, The Problem of "Hoarding"]


-----------------------------
Work in progress following...
-----------------------------

The degree of saleability can be defined by the following characteristics: (1) scarcity; (2) portability; (3) durability; (5) divisibility; (6) malleability; (4) homogeneity; (8) censorship resistance. Each of those attributes will be analyzed briefly and compared to the attributes of Bitcoin.

(6) Malleability is the useful attribute of a money, that it can be reshaped to fit a specific need over and over again with limited costs. Similar to the attribute of divisibility, the value of the good increases, with lower costs of transforming it. 

Gold can be transformed into jewelry, which increases its artistic value, minted into coins to make denominations more accessible, or cast into gold bars, to provide a high density of value.

Bitcoin has an intrinsic stack based programing language called script.footnote:[More on Bitcoin script at https://en.bitcoin.it/wiki/Script] For security reasons, it is not turing complete, however it still provides vast opportunities to build complex smart contracts. Following are three examples. For the most basic Bitcoin transaction, a one input - one output function, the spender must provide a new destination address as the output, and a cryptographic signature that proves ownership of the spent input embedded in the Bitcoin script. In a M-of-N multisignaturefootnote:[More on Bitcoin multisig at https://en.bitcoin.it/wiki/Multisignature, see the https://misthos.io multisig wallet] [multisig] address, the UTXO can only be spent with the proof of ownership [signature] of M private keys. Cooperation of M signatories is thus required in order to move the coins. nLockTime and CheckSequenceVerifyfootnote:[More on nLockTime and CheckSequenceVerify https://bitcoin.org/en/developer-guide#locktime-and-sequence-number] indicate the earliest time, when a transaction can be added into the blockchain, thus providing time based contracts. Even though those three functions seem trivial, they can solve countless problems with trusted third party custodians. Bitcoin is programmable money, thus highly malleable and the implications are not yet fully grasped.

(4) If the economy has several different moneys, all goods have to be priced in each and every of those moneys. This increases transaction costs through, decreases the number of possible transactions with each money and makes long term calculation more difficult. Thus there is a natural tendency towards one single unit of account in which all goods are being priced. This effect not only means that only one currency will be used, but that those money units themselves are homogeneous.

This is achieved in fiat money with legal tender laws, a debtor is forced to accept any one fiat money unit, regardless the specific serial number. 

One gold atom is indistinguishable from another, therefore it is generally accepted. However, there is a difference in the appearance of those gold atoms, they can be dust, casted into coins or bars. This decreases the homogeneity by the cost of reshaping the metal.

In Bitcoin, one Bitcoin is one Bitcoin, regardless which one it is, as long as the transaction output is unspent, it is a valid Bitcoin. But because of a lack of anonymity in Bitcoin, the transaction history of each UTXO is publicly available. On the human level, they can thus be distinguished, for example can and do centralized exchanges censor the transaction of known and unwanted individuals. On protocol level, this has never happened. Bitcoin has homogeneity on a protocol level, but the unique coins can be identified by humans.

Results of a good money (1) The general acceptability or cognizability (7) purchasing power stability

(1) The general acceptability or cognizability of a MoE is determined by the number of actors in the economy that are willing to trade at any given time their goods at a specified exchange rate for that MoE. The number of possible economic transactions increase exponentially with the entrance of each new actor and this network effect increases each individual valuation of the MoE.footnote:[Carl Shapiro, Hal R. Varian. Information Rules - A Strategic Guide to the Network Economy] The more people use the MoE, the less economic transactions are necessary, therefore the higher its value – and with increased value, more people use it and the less economic transactions are necessary. On the micro scale for an individual the MoE has achieved its highest valuation, when every possible good can be exchanged for conveniently and at a good price. This can be achieved in an isolated and self sufficient economy even with only a few individuals partaking in it. To receive high valuation in the macro scale of the entire economy, the MoE needs to be accepted widely and thoroughly and not just by a few individuals. If only one MoE is used on the macro scale, all the prices can be denominated in this one good, making it the unit of account. However, if multiple MoEs are used, the prices of all goods have to be denominated in several different MoEs.footnote:[Murray N. Rothbard. “11. Coexisting Moneys” Chapter 2: Money in a Free Society. What has Government Done to Our Money]

The governments has to force people with legal tender laws to use the currency at least to pay back debt and taxes [i.e. theft]. This proofs, that fiat currencies are in every shape or form inferior to sound money such as gold or Bitcoin, because if they were not, governments would not have to force the economy to use it. If the costs of defying the immoral government intervention is higher than the obstruction of the inferior currency, it is rational to keep using it. However, as soon as there is a much superior currency available, a rational market participant will carry the costs of revolution. 

For a long time in human history, gold was an universally accepted money, regardless of the continent, society or language, eventually the economy moved towards gold as money. With the advent of a gold backed paper currency, the high weight, the big disadvantage of gold, was circumvented. In the 18th century, we came closest to a universal global gold standard as ever. This might have been the cause for all the great inventions in those free and prosperous years. 

Bitcoin is already used by many individuals, including this author, as their sole MoE of choice for a majority of their economic transactions. The number of possible economic transactions have so far increased exponentially with more and more merchants offering their goods and services for Bitcoin or any other cryptocurrency. Regardless of the fast growth of acceptance, at the time of writing Bitcoin can not be considered a general accepted MoE in the macro economy. Bitcoin is generally not the unit of account for everyday consumption goods. However, most altcoins are traded against Bitcoin, so it can therefore already be regarded as the unit of account in cryptocurrency trading.

(7) A money is not a good that is not used now, but in an uncertain future exchange. A good has a stable purchasing power, when the exchange value does not change over time. If the good is subject to drastic price volatility, it is not clear which quantity of the good is needed for a specific trade, and thus an additional risk premium and more savings are required. Furthermore a wildly fluctuating value of money, hinders the long term coordination of production stages and the calculation of prices. As with all prices, the purchasing power is determined by the law of supply and demand. The demand for money depends on the three use cases [MoE, SoV, UoA] and the attributes explained in this chapter.

Although the main goal of incumbent central banks is purchasing power stability, historically, government fiat money tends towards a price of 0, due to unchecked money creation which leads to hyper-price-inflation.footnote:[See chapter on money supply and inflation.] For example, the US Dollar has lost over 98% of its purchasing power in the last 100 years.
Gold has a historic annual flow-to-stock ratio of 1.77%,footnote:[See Graphic ms-growth, Saifedean Ammous] so the increase in supply is limited and steady. This leads to a rather stable purchasing power of gold throughout the ages. The popular saying goes, that a one ounce gold coin could buy you a tailor made garn in ancient Rome, and today a one ounce gold coin can still buy you a bespoke London suit.

Due to Bitcoin’s extreme scarcity, the supply is very limited and the emission rate is publicly available and unchangeable. Bootstrapping a new currency requires lots of speculation and is a risky undertaking. Historically, the price volatility of Bitcoin is upward trending between 0.8% and 16%.footnote:[Bitcoin Volatility Index https://www.buybitcoinworldwide.com/volatility-index/]

Bitcoin is by design very decentralized,footnote:[Paul Stortz. Measuring Decentralization 2015 at www.truthcoin.info/blog/measuring-decentralization/] no one party controls any aspect of the protocol. Specifically to send a transaction to the network, only one independent node out of the thousands has to receive it. There are many different options to send a transaction, including standard Internet connection, encrypted TOR connection, satellite uplink, radio receivers, pictures, and even carrier pigeons. It is almost impossible to forcefully block all the options available, as one transaction way will inevitably reach one node. Once one node receives the transaction it subsequently propagates it to its peers and they propagate it further, thus the gossiping network shares the transaction with all nodes on the network securely and inevitably.footnote:[Andreas Antonopoulos. “Bitcoin Relay Networks” Chapter 8: The Bitcoin Network. Mastering Bitcoin 2016] footnote:[Fadhil, Owen, Add. Bitcoin Network Measurements for Stimulation Validation and Parameterisation 2016] The transaction is verified, saved and secured on thousands of- individual computers and eventually added to the public and common blockchain. Censorship of Bitcoin transactions is therefore nearly impossible. The entrance to Bitcoin is trivial and open, a private key is a 2256 bit random number that can be generated by flipping a coin, writing a poem, or using secure hardware. It only requires simple mathematics and cryptography to generate a functional Bitcoin Address that can instantly receive any amount transacted from anywhere in the network. There is no censorship through know your customer and the anti money laundering directives that are forced upon the incumbent fiat market.
