Forks
=====

All aspects of Bitcoin are fully transparent and open source, thus anyone who is interested has access to the Bitcoin Core implementation and source code.footnote:[https://github.com/bitcoin/bitcoin] As code is speech and a non-scarce good,footnote:[See chapter on scarce and non-scarce goods] it can be copied, adapted, and changed at barely any marginal cost. A problem with coins that trade on novelty (rather than utility) is that the market creates novelty faster than they can.footnote:[Tuur Demeester] The code repository can easily be forked off, so to experiment with changes in the code base without affecting the existing consensus implementation. This code fork is not necessarily consensus critical and can be done without permission. A change in the code can be proposed to be pulled back into the reference client, but this is done after rigorous peer review and only when majority consensus is reached. Ultimately, the end user alone is deciding which software he is running and no malicious actor can force him to install any update.footnote:[See chapter on why to run a full node]

Bitcoin is consensus code that leads to a schelling point, a standard that people will tend to use in the absence of communication, thus a consensus fork is “a divergence in the implementation of the verification consensus rules [which] can impede the expected eventual convergence of the network in a single chain that has the most proof of work and also satisfies the rules. This can be intentional or be caused by a bug in consensus validation re-implementations.”footnote:[Jorge Timón, BIP 99, “Motivation and deployment of consensus rule changes (soft/hard-forks)”]

A hardfork is a change to the Bitcoin protocol which loosens restrictions, that is that some previously invalid transactions are now considered valid. This might include increase of the block size,footnote:[https://github.com/bitcoin/bitcoin/blob/27765b6403cece54320374b37afb01a0cfe571c3/src/consensus/consensus.h#L16] signatures operations in the block,footnote:[https://github.com/bitcoin/bitcoin/blob/27765b6403cece54320374b37afb01a0cfe571c3/src/consensus/consensus.h#L18] or the maximum number of coins, footnote:[https://github.com/bitcoin/bitcoin/blob/c0ddd32bf629bb48426b0651def497ca1a78e6b1/src/amount.h#L31] but there are no limits on what could be changed. Because “old” nodes will consider these “new” nodes as violators of the original consensus, each individual node will block and ostracize these aggressors immediately. Even if 99% of nodes accept these new rules and implement the software, they cannot make the 1% upgrade, and these will still run the original consensus rules. Thus even with a hyper majority update, the change is a hard fork and the minority network will continue. After the fork, there will be two different networks and blockchains continuously running. Only the self sovereign nodes themselves decide which rules to adhere to, and the Schelling point is the Nakamoto consensus. Usually, the UTXO set of the old chain will be utilized as the starting UTXO set of the forked chain, thus every user who had control of Bitcoin before the split will gain additional forked coins. These additional UTXO might be considered a gift by the developers of the new coin to incentivize users to implement the protocol changes. Some projects that fork the Bitcoin consensus argue that this new set of rules is considered to be the true Bitcoin, this is fallacious in many ways. As Satoshi said: “The nature of Bitcoin is such that once version 0.1 was released, the core design was set in stone for the rest of its lifetime.”footnote:[Nakamoto (June 2010) https://bitcointalk.org/index.php?topic=195.msg1611#msg1611] A key attribute of Bitcoin is it’s unchangeability,the fact that individual nodes can not be forced to modify their software and rule set. Once the precedence of a consensus critical change is made, the risk of another change is more likely, as seen with the BCash hardfork, the following splintering and continues forks.
This is in part due to the inherent centralizing nature of a hardfork that is being advocated for by a minority group. Bitcoin does not change precisely because it is leaderless, and any change requires strong avocation of someone.

Due to the value involved in hardforks, a technical debate often shifts to a political one. Individuals who invest much time and effort into developing a hardfork often aspire to become a leader. As humans often look for guidance and leadership, especially in highly complex environments, these people often rise to a new "Satoshi"-like status. They're assumed to be knowledgeable and often get a significant say in decisions they shouldn't necessarily be involved in. Many dubious personalities went down this path in the past but haven't been able to gain any long term significant influence in the original Bitcoin project.

A softfork is a change of the rule set which tightens the parameters, this means that the all the new transaction are still considered valid under the original consensus. This means that these new clients are restraining themselves and putting additional rules in place which are more constrained than the previous ones. Such a rule change is backwards compatible, because old nodes see this new rule set as valid. Contrarily to a hard fork, a soft fork can be applied by only one individual node, as this node doesn't break consensus. This is an opt in model, thus all users voluntarily agree to constraint their own set of rules. And those that do not want to play by these rules, stick to the original consensus, but stay on the same network and Blockchain as those that support the soft fork. Although the full nodes have complete control over their rule set and can change it any time, the resulting blockchain is only secure against reorganisation and double spending attacks, if the majority of hashing power is honest. Thus, the nodes have to incentivize enough miners to support this chain, which is done by coinbase reward and transaction fees.

After years of research and development, it was clear that segregated witness is an overall net positive for the entire network. Segwit fixes the malleability bug, which makes second layers solutions like the lightning network and further complex smart contracts such as charming coin joints possible. Because the signature part is segregated from the block itself this, this is an increase in the block weight and therefore increases the maximum amount of transactions per second. Furthermore, with the versioning upgrade mechanism, other signature schemes such as Schnorr signature or BLS can be added in the future with another soft fork. Only after enough research and with sufficient development and peer review did the core process push for a update in the consensus rules. A dedicated group of individuals can manifest this change in the Bitcoin consensus protocol, as long as they do not violate the rules of other full nodes. Initially, the upgrade mechanism was deployed in a way where miners had to signal the usage and agreement to the segwit soft fork. As these service providers tried to block and delay the segwit activation, sovereign nodes banded together and declared to no longer accept PoW of miners who were actively blocking the voluntary softfork. The act of not doing business with another individual is fundamentally based in voluntary interaction and the Right to be left alone. As long as the user activated soft fork does not break the consensus rules of other individual note it is ethically righteous. The segwit uasf shows that sovereign full nodes are in full control of their own consensus implementation, however it is wrong to break the rules previously agreed upon.

After segwit got activated, a small group of individuals tried to implement a new code repository as the main consensus reference with a hard fork increasing the block size to 2 megabyte. This hard fork was to be implemented and activated by the hatching power of minors signalling they're support. This miner activated hard fork stands as to complete antithesis to the user activated soft fork. A small minority of researchers developers and Enterprise mainly sponsored by Bitmain tried to introduce a change to consensus which would break the previously agreed upon ruleset. Only after a massive push back from the community [#No2X] did the small minority give up and stop their effort to force a rule change on everyone else. Due to serious flaws in the code and an off by one error the hardfork would never have taken place any how. Regardless, these individuals could never have forced other fool notes to accept and play by these new set of rules the schelling point of Bitcoin is the status quo.

As the core attribute of Bitcoin is financial self sovereignty and therefore the unchangeability of consensus rules, upgrades and improvements to the network are always going to be a contentious matter. It is curious to see how upcoming coming changes are proposed and handled in the core process. There are still many features to be added to bitcoin primarily regarding its privacy and fungibility aspects. Although the research and development of tools such as confidential transactions and schnorr signatures are advanced and currently going through rigorous peer review, implementing these major changes will be a heavily debated topic worth further study. The main challenge will be to introduce these features in a non contentious but voluntary matter, primarily with a soft fork.
