Forks and Altcoins
==================

All aspects of Bitcoin are fully transparent and open source, thus anyone who is interested has access to the Bitcoin Core implementation and source code.footnote:[https://github.com/bitcoin/bitcoin] As code is speech and a non-scarce good,footnote:[See chapter on scarce and non-scarce goods] it can be copied, adapted, and changed at barely any marginal cost. The code repository can easily be forked off, so to experiment with changes in the code base without affecting the existing consensus implementation. This software fork is not necessarily consensus critical and can be done without permission. A change in the code can be proposed to be pulled back into the reference client, but this is done after rigorous peer review and only when majority consensus is reached. Ultimately, the end user alone is deciding which software he is running and no malicious actor can force him to install any update.footnote:[See chapter on why to run a full node]

Bitcoin is consensus code that leads to a schelling point, a standard that people will tend to use in the absence of communication, thus a consensus fork is “a divergence in the implementation of the verification consensus rules [which] can impede the expected eventual convergence of the network in a single chain that has the most proof of work and also satisfies the rules. This can be intentional or be caused by a bug in consensus validation re-implementations.”footnote:[Jorge Timón, BIP 99, “Motivation and deployment of consensus rule changes (soft/hard-forks)”]

A hardfork is a change to the Bitcoin protocol which loosens restrictions, that is that some previously invalid transactions are now considered valid. This might include changes to the block structure, difficulty rules or the inflation schedule, but there are no limits on what will be changed. Because “old” nodes will consider these “new” nodes as violators of the original consensus, each individual node will block and ostracize these aggressors immediately. Even if 99% of nodes accept these new rules and implement the software, they cannot make the 1% upgrade, and these will still run the original consensus rules. Thus even with a hyper majority update, the change is a hard fork and the minority network cannot be stopped. After the fork, there will be two different networks and blockchains continuously running. Usually, the UTXO set of the old chain will be utilized as the starting UTXO set of the forked chain, thus every user who had control of Bitcoin before the split will gain additional forked coins, dubbed Bitcoin dividends.footnote:[Term proposed by Adam Meister] These additional UTXO might be considered a gift by the developers of the new coin to incentivize users to implement the protocol changes. Some projects that fork the Bitcoin consensus argue that this new set of rules is considered to be the true Bitcoin, this is fallacious in many ways. As Satoshi said: “The nature of Bitcoin is such that once version 0.1 was released, the core design was set in stone for the rest of its lifetime.”footnote:[Nakamoto (June 2010) https://bitcointalk.org/index.php?topic=195.msg1611#msg1611] A key attribute of Bitcoin is it’s unchangeability, and once the precedence of a consensus critical change is made, the risk of another change is more likely. This is in part due to the inherent centralizing nature of a hardfork that is being advocated for by a minority group. Bitcoin does not change precisely because it is leaderless, and any change requires strong avocation of someone.

Due to the value involved in hardforks, a technical debate often shifts to a political one. Individuals who invest much time and effort into developing a hardfork often aspire to become a leader. As humans often look for guidance and leadership, especially in highly complex environments, these people often rise to a new "Satoshi"-like status. They're assumed to be knowledgeable and often get a significant say in decisions they shouldn't necessarily be involved in. Many dubious personalities went down this path in the past but haven't been able to gain any long term significant influence in the original Bitcoin project.
