Free Exchange and Interventionism
=================================

Why do people exchange freely and voluntarily all the time. If you look throughout history, there is a prominent display of free and voluntary exchange between individuals who walk away after this trade better of because otherwise they wouldn’t do it freely. Why is that? Let us examine the following hypothetical construct of Alice and Bob are living on a lonely island:

Alice is a very skilled apple picker, gathering tenty apples per hour, but not a good berry picker, only gathering 30 berries per hour. Bob can gather 80 berries per hour, but due to a lack of skill, can only gather ten fish per hour. If the two decide to work only for themselves for two hours, Alice can produce twenty apples and 30 berries, Bob can produce ten apples and 80 berries.

However, they can decide to specialize individually on the task where they are marginally better, so Alice producing fourty apples, and Bob solely gathers 160 berries. On Alice’ individual preference scale, she prefers 80 berries over ten apples, on Bob’s individual preference scale, he prefers ten apples over 80 berries. They have a unique opportunity to engage in a voluntary trade of one fish for 80 berries. After this exchange, Alice has twenty apples and 80 berries, Bob has twenty apples and 80 berries, both are better off, making the trade mutually beneficial. Both will walk away saying ‘thank you’ and appreciating the work the other party has done, it is respect, corporation and peace.

The free market is so beautiful, precisely because it’s mutual beneficiary throughout the entire process. One can only express the individual's preference scale with the action of exchange, and if this is done freely and voluntarily, it implies the higher value of the traded good. The production of all individuals and the entire economy is increased by free exchange. Specialization is encouraged, division of labor is encouraged, free trade is encouraged.

It implies the natural right of the individual to do with his property as he pleases, as long as he doesn’t harm any other sentient being. Clearly, exchanging the property for a different good is an inherent part of this right, and to deny it is to imply expropriation and slavery.

As Rothbard put it, there are three different types of intervention: autistic, binary, and triangular. Each inherently breaks the beauty of the free market and is not at all mutually beneficial: one individual or group of individuals use violence or the threat thereof to become the master: the tyrant or state, the other individual or group of individuals become the oppressed: the slave. Any form of intervention is thus a violation of Property Rights and Natural Law, and thus uneconomical and immoral. 

(1) In an autistic interventionfootnote:[Rothbard, Power and Markets, Chapter 2 Fundamentals of Intervention] the state denies the individual to use his property in a way that is not in accordance with the states degree, although the individual would not hurt anyone else in his intended action. Prohibition is an example where the state punishes the righteous production and consumption of a good, such as alcohol or marijuana. Thus, the state implies a higher right to the individuals property and his person, which of course fundamentally breaks the natural law. The state gets the outcome it intended and receives its higher value, however the oppressed individual is worse of no matter his intention of adherence of this man made ‘law’. In the case that he did not want to produce or consume the forbidden good, due to the implied threat of violence, and in the case that he wanted to produce or consume the good, because he is forcefully prohibited from partaking in this action with his own property to gain additional value. In a free market, the individual will be counseled, suggested and persuaded peacefully and non coercively without the threat of violence, to stop the action, but the individual can at any time deny and ignore the counseling, he only accepts it if it's of value to him, making it again a mutually beneficial interaction.

(2) In a binary interventionfootnote:[Rothbard, Power and Markets, Chapter 4 Binary Intervention: Taxation and 5 Binary Intervention: Government Expenditures] the state forces or coerces the individual to interact in exchange with the state, so the individual has no way of declining. Taxation is an example where the state forcefully expropriates, without the explicit consent, a portion of the individuals income (theft) and product of labor (slavery). Again the state gets the higher valued outcome, the ownership of the individuals property, and the individual is again oppressed regardless of his intention to exchange or not with the state. Even if the individual was voluntarily intending to pay the contribution, the threat of violence inevitably decreased his valuation, and of course if he did not intend to pay the contribution, he was forcefully removed from his rightful ownership and is therefor by definition worse of. In some occasions, the individual or society at large might get back some or all of the stolen property in form of grants or services, public education, roads or security. But nevertheless, the property was first involuntarily stolen and is thus never employed in the individual's highest valuation. Due to costs of bureaucracy the aggregated amount of stolen property is always higher than the aggregated amount of employed public grants and services. In the free market, all exchanges are engaged in voluntarily and are therefor not taxation, but rather a payment for a provided service, exactly the same to the exchange of any other good or service.

(3) In triangular interventionfootnote:[Rothbard, Power and Markets, Chapter 3 Triangular Intervention] the stated forces two individuals to only engage in trade with the rules set forth by and the permission of the state, examples are registration, licensing and forced contract covenants. The state gets the higher valued outcome of control, and the individuals get oppressed again even if they intended to obey the ‘law’ due to the threat of violence, and also if they did not want to engage in the contract forced upon them by the state. Triangular intervention can be sub divided into price controls and product controls. The aggressor can either set a minimum price, which will hurt the customer as he must pay more than he would voluntarily choose to, thus less will be consumed; or a maximum price, which means that entrepreneurs might have to carry a loss as not all their expenses are covered. Regardless, as this dictated price is not the voluntarily chosen market price, it is inherently not mutually beneficial and thus destroys resources and capital. In regards of money, price controls inevetably lead to Gresham's law.footnote:[Refer to chapter on Gresham's law] Also, the state can manipulate the nature of production directly, rather than the terms of exchange. This is that the aggressor prohibits the production or sale of a certain product, which will again lead to a net loss for all participants. The consumer looses utility as he cannot acquire the good with which he could satisfy his desires, and the producer who is prohibited from earning the revenue that the exchange would have brought him. The only ones that will benefit from this coersion, is the aggressor himself, partly from the tax or licences which is collected, or from the twisted satisfaction of surpressing others. 
