Gresham’s Law
=============

On the free market, a good will always be valued according to the individuals subjective preferences. Assuming two goods are equal, they will be valued the same. If there are two almost identical coins, each in pristine conditions and with precisely one ounce of gold, they will be valued equally by any market participant, thus the coins are fungible. Suppose these coins have experienced degradation and chipping, now only containing 0.9 gold ounces. In a voluntary exchange, the coin will only be worth 90% of the previous one ounce of gold.

However, if the government introduces legal tender laws as a form of price control, it decrees that the worn coins have to be valued equally to the new ones and they must be accepted as equal in payment of debts. The old coins are thus artificially overvalued, and new coins undervalued. This act sets a maximum price on one type of money in relation to another. Maximum prices usually cause a shortage, that is the undervalued good coin will be hoarded while the overvalued old coin will be solely used in exchange.

Gresham’s law says that “money overvalued artificially by government will drive out of circulation artificially undervalued money.” Thus “there is nothing less fit to be left to the action of competition than money.”footnote:[W. S. Jevons 1875, Money and the Mechanism of Exchange] It is important to emphasize that Gresham’s law only applies to different kinds of money in between which is a fixed rate of exchange enforced by law.footnote:[F. A. Hayek, Studies of Philosophy, Politics and Economics, Routledge & Kegan Paul, London and Chicago, 1967]footnote:[F.W. Fetter, Some Neglected Aspects of Gresham’s Law, Quarterly Journal of Economics, XLVI, 1931/2] If due to the law two different moneys are treated as substitutes for the payment of debts, creditors are being forced to accept a coin of smaller gold content in place of one with a larger content. Thus, debtors will only pay with the smaller coin and use the larger as a store of value.

Speculative Attack
==================

As explained elsewhere, as the demand for fiat currency increases, it will initially increase its value, which will incentivize central banks and governments to produce additional units of money. This will increase the money supply, lowering the stock-to-flow ratio and thus decreasing the purchasing power of the fiat currency. The increased inflation rate will incentivize the accumulation of additional debt, which will again increase the money supply, further weakening the currency.

Let’s assume that there is a sound and hard monetary alternative to the fiat money, and that the fiat debtors will exchange their fiat currencies for the sound money. This increases the demand for the sound money, which will due to a fixed stock-to-flow ratio increase its purchasing power.

The rational action for economic participants would thus be to go into debt in the weak currency and accumulate sound money. “As soon as the public became familiar with the new possibilities, any deviations from the straight path of providing an honest money would at once lead to the rapid displacement of the offending currency by others.”footnote:[Hayek, 1974 Denationalisation of Money, Free trade in Money, p.23]

This is not just a hypothetical construct, as there are countless examples of people taking on fiat debt and mortgaging their house to buy even more Bitcoin. Curiously, so far the stock-to-flow ratio of fiat money was higher than that of Bitcoin, but only in the early days. Especially with the next halving in 2020, the inflation rate in Bitcoin will be much lower than that in fiat, further increasing this effect.


