Gresham’s Law
=============

On the free market, a good will always be valued according to the individuals subjective preferences. Assuming two goods are exactly equal, they will be valued the same. If there are two almost identical gold coins, each in pristine conditions and with precisely one ounce of gold, they will be valued equally by any market participant, thus the coins are fungible. Suppose these coins have experienced degradation and clipping,footnote:[Rothbard, Case Against the FED, Chapter on Legalized Counterfeiting], now only containing 0.9 gold ounces. In a voluntary exchange, the coin will only be worth 90% of the previous one ounce of gold.

However, if the government introduces legal tender laws as a form of price control, it decrees that the worn coins have to be valued equally to the new ones and they must be accepted as equal in payment of debts. The old coins are thus artificially overvalued, and new coins artificially undervalued. This act sets a maximum price on one type of money in relation to another. Maximum prices usually cause a shortage, that is the undervalued good coin will be hoarded while the overvalued old coin will be solely used in exchange.footnote:[Hazlitt, What You Should Know About Inflation, Chapter False Remedy: Price Fixing]

Gresham’s lawfootnote:[Rothbard, Man Economy and State with Power and Markets, Chapter 12 The Economics of Violent Intervention in the Market, Part 5 Triangular Intervention: Price Control] says that “money overvalued artificially by government will drive out of circulation artificially undervalued money.” Thus “there is nothing less fit to be left to the action of competition than money.”footnote:[W. S. Jevons 1875, Money and the Mechanism of Exchange] It is important to emphasize that Gresham’s law only applies to different kinds of money in between which is a fixed rate of exchange enforced by law.footnote:[F. A. Hayek, Studies of Philosophy, Politics and Economics, Routledge & Kegan Paul, London and Chicago, 1967]footnote:[F.W. Fetter, Some Neglected Aspects of Gresham’s Law, Quarterly Journal of Economics, XLVI, 1931/2] If due to the law two different moneys are treated as substitutes for the payment of debts, creditors are being forced to accept a coin of smaller gold content in place of one with a larger content. Thus, debtors will only pay with the smaller coin and use the larger as a store of value.

As the crypto currency market is free from most government interventions, Gresham’s Law does not apply to the different digital assets. However, there is government coercion with legal tender laws in fiat money, which artificially overvalues state currencies. If Alice has both fiat and bitcoin in her possession, and she is seeking to exchange them for goods and services, it is rational that she will first spent the fiat money, as its price is artificially increased. Further, as the fiat money base is continuously inflated, it will continue to depreciate in purchasing power, thus incentivizing spending over rational saving.footnote:[Hülsmann, The Cultural Consequences of Fiat Money] Alice will retain her sound and hard bitcoin, until she no longer has any artificially overvalued fiat. At the point where she has fully moved to the voluntary and sound economy of bitcoin, her time preference has decreased accordingly and she will adjust her spending patterns. Now she will willingly exchange her sound bitcoin for precious goods and services which she actually needs, and not because she is artificially incentivized to over consume. So far, few individuals have fully thrown off all their fiat bags, but those that did, now experience the total realignment of their time preference to a voluntary market economy.

“Historically, it has been good, strong currencies that have driven out bad, weak currencies. Over the span of several millennia, strong currencies have dominated and driven out weak in international competition. The Persian daric, the Greek tetradrachma, the Macedonian stater, and the Roman denarius did not become dominant currencies of the ancient world because they were "bad" or "weak." The florins, ducats and sequins of the Italian city-states did not become the "dollars of the Middle Ages" because they were bad coins; they were among the best coins ever made. The pound sterling in the 19th century and the dollar in the 20th century did not become the dominant currencies of their time because they were weak. Consistency, stability and high quality have been the attributes of great currencies that have won the competition for use as international money.”footnote:[Robert Mundell, “Uses and Abuses of Gresham’s Law in the History of Money”]

Speculative Attack
==================
As the demand for fiat currency increases, it will initially increase its value, which will incentivize central banks and governments to produce additional units of money. This will increase the money supply, lowering the stock-to-flow ratio and thus decreasing the purchasing power of the fiat currency. As the money is now less valuable, it is also cheaper to borrow money and pay back at a later point in time at a further decreased purchasing power. The increased inflation rate will thus incentivize the accumulation of additional debt, which will again increase the money supply, further weakening the currency. Thus, the liabilities side of Alice’s balance sheet will increase in mortgages and consumer loans.

Let’s assume that there is a sound and hard monetary alternative to the fiat money, and that the fiat debtors will exchange their fiat currencies for the sound money. This increases the demand for the sound money, which will due to a unchanging stock-to-flow ratio increase its purchasing power. Thus simultaneously, the fiat currency will decrease in purchasing power as additional debt is taken on, and the sound money will increase in value. Those speculators now hold more valuable money and have to pay back the less valuable money, netting a substantial profit. Thus, the asset side of Alice’s balance sheet will increase in total bitcoin hodlings.

“The effect of people, businesses, or financial institutions borrowing their local currency to buy bitcoins is that the bitcoin price in that currency would go up relative to other currencies. […] The central bank would have to either increase interest rates to break the cycle, impose capital controls, or spend their foreign currency reserves trying to prop up the Rupee's exchange rate. Only raising interest rates would be a sustainable solution, though it would throw the country into a recession.”footnote:[Pierre Rochard, Speculative Attack]

The rational action for economic participants would thus be to go into debt in the weak currency and accumulate sound money. “As soon as the public became familiar with the new possibilities, any deviations from the straight path of providing an honest money would at once lead to the rapid displacement of the offending currency by others.”footnote:[Hayek, 1974 Denationalisation of Money, Free trade in Money, p.23]

This is not just a hypothetical construct, as there are countless examples of people taking on fiat debt and mortgaging their house to buy even more bitcoin. Curiously, so far the stock-to-flow ratio of fiat money was higher than that of Bitcoin, but only in the early days. Especially with the next halving in 2020, the inflation rate in Bitcoin will be much lower than that in fiat, further increasing this effect.

“A hyperbitcoinization event will be much quicker than a hyperinflation event. I have two reasons for this. First, the government will have a much greater difficulty preventing bitcoins from entering the country due to the impotency of capital controls upon it. Second, hyperinflation is inherently an attempt to fool people, whereas hyperbitcoinization is quite regular and predictable (at least by comparison). Therefore people will more easily see that they had better switch over. Thus, as fast as hyperinflation is, hyperbitcoinization will be even faster.

Hyperbitcoinization will not disrupt the economy to nearly the same degree as hyperinflation. The currency is the instrument of the division of labor, and hyperinflation makes it unreliable and forces people to use worse alternatives. In a hyperbitcoinization event, people switch from a fundamentally inferior currency to a superior one, whereas in a hyperinflationary event people will only switch to a new currency once the old currency becomes worse than the next best alternative, such as gold or detergent. Hyperbitcoinization should be accompanied by a rapid improvement in productivity and wealth.”footnote:[Daniel Krawisz, Hyperbitcoinization]
