Lightning Network
==============
As the blockchain is stored and verified by every full node in the network and updates to this data structure take 10 minute intervals, the blockchain is an inefficient and slow database. However the blockchain is extremely useful for dispute resolution that is to effectively prove who owns which UTXO. The security and censorship resistance of the base layer blockchain can be leveraged in further protocols layered on top. There are different scaling proposals, one of the most prevalent being the lightning network of interconnected payment channels.

The first versions of a payment channel was introduced by Satoshi Nakamoto in version 0.1 of the Bitcoin client, however this sequence numbers scheme was not trustless and secure. Ever since then, lots of research and development has gone into payment channels and by now there are several trust minimised and trustless payment channel. 

On a high level Alice and Bob both paid 5 Bitcoin in a 2 out of 2 multi signature, were both Alice and Bob control their corresponding private key. After this opening transaction has confirmed and after sufficient accumulated proof of work, Alice and Bob can shift the current state of this multi-signature wallet without broadcasting an on chain transaction. When Alice sends one bitcoin, she signs a new possible settlement transaction of the multisig with Alice 4 and Bob 6. Additionally, Alice provides Bob with a revoke hash pre image, which would give Bob control of Alices 5 bitcoin should she publish the old state of the payment channel. Thus, the should Alice try to steal bitcoin from Bob, Bob can take all her Bitcoin as punishment. As long as Alice and Bob do not close the payment channel, they can iteratively update the current state of this multisig. The speed of transaction is limited to the speed of signing and broadcasting a transaction which can be done millions of times per second.

The lightning network is a protocol that intralinks these individual payment channels, so that Alice can send money to Dave, although she does not have an open direct payment channel to him. Alice can use the capacity of Bob's and Charlie's payment channels to route her payment through to Dave. A=B B=C C=D For the service of routing the payment, providing liquidity and being online Bob and Charlie can charge a minuscule fee paid by Alice. This fee is a counterparty risk free interest rate.

In a sense, payment channels and the Lightning network is a novel approach to introduce a trustless ways of sending and accepting 0 confirmation bitcoin transactions. It is a new payment mechanism utilising the sound money bitcoin and it does not create a new currency. The lightning network is thus a layer on top of the sound money Bitcoin consensus and is inherently voluntary opt-in. As the total capacity of the payment channels is registered and verified in the base layer blockchain, there is no inflation of the money supply. Rather the base layer currency is being morphed in such a way that it gains additional features. Similarly to the gold, which can be used either in gold dust, minted to coins or smelted into bars, each with their inherent features and trade-offs based upon the sound money gold.
