The positive externalities of Bitcoin Mining
============================================

One of the major concerns expressed endlessly in mainstream media, is the rather high energy consumption of PoW. The common argument goes, that by now, Bitcoin is using more electricity than [insert your favorite small country here],footnote:[The Economist July 2018 https://www.economist.com/the-economist-explains/2018/07/09/why-bitcoin-uses-so-much-energy]footnote:[CNBC May 2018 https://www.nbcnews.com/tech/tech-news/study-claims-bitcoin-uses-much-energy-ireland-not-so-fast-n875211]footnote:[The Guardian November 2017 https://www.nbcnews.com/tech/tech-news/study-claims-bitcoin-uses-much-energy-ireland-not-so-fast-n875211]footnote:[Forbes, April 2018 https://www.forbes.com/sites/shermanlee/2018/04/19/bitcoins-energy-consumption-can-power-an-entire-country-but-eos-is-trying-to-fix-that/]footnote:[Bitcoin actually uses less electricity than Christmas lights in the US, which is at over 6.63 TWh/yr. https://www.energy.gov/sites/prod/files/maprod/documents/Energy_Savings_Light_Emitting_Diodes_Niche_Lighting_Apps.pdf] and that Bitcoin is even a serious climate threat.footnote:[The Guardian, January 2017 https://www.theguardian.com/technology/2018/jan/17/bitcoin-electricity-usage-huge-climate-cryptocurrency]

PoW is used so to make the reordering of the transaction history, i.e. double-spending, expensive. Once a transaction is propagated by the nodes on the network, miners package several of these transactions from the mempool in an individual candidate block, which also contains a reference to the most recent valid block and a timestamp. A block is only valid, when the SHA256-hash of the block header is below a certain target difficulty. This target is a 256-bit number that is known and verified by all nodes on the network. According to Nakamoto Consensus, the genesis block had a difficulty target of 0x00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, and this maximum target is the lowest possible difficulty. In order to increase stability and lower latency to transaction confirmation, the network strives to keep an average block time of 10 minutes. Every 2016 blocks nodes compare the actual time it took to generate these blocks with the previous two week goal and change the target for the next 2016 blocks. The target for the following 2016 blocks is modified by the percentage differences: old_difficulty*(2 weeks)/(time the past 2015 blocks took). Thus, if in a 2016 block period the total number of hashes per second has increased, it took less than 20160 minutes to generate the blocks, thus the difficulty target will adjust downwards. Vice versa, if in a 2016 block period the total number of hashes per second has decreased, it took more than 20160 minutes to generate the blocks, thus the difficulty target will adjust upwards.

Miners have capital expenditure in computer hardware, and operational expenditure in electricity. Entrepreneurs will only take on expenditures if they  forecast that there is potential profit after selling the produced good to consumers. The good that miners are producing is valid and secure block space. The user pays for inclusion into this block space with every transaction, denominated in Satoshis per virtual Byte.footnote:[BIP141] The more byte a user wants to include in the blockchain, the higher the total fee paid to the miner. Miners choose those transaction for their individual candidate block, which pays them the most Satoshis per vByte. In addition to the transaction inclusion fee, miners are subsidized by newly created bitcoin, thus they are the ultimate benefactor of the inflationary monetary structure. According to Nakamoto Consensus, a valid block can only have a coinbase transaction with at the most 50 BTCfootnote:[halfing every 210.000 blocks] + the sum of all outputs minus input.footnote:[aggregated transaction fees]

Ultimately, miners receive the coinbase reward if and only if they produce a valid block which does not break consensus. If they produce a block that is below the difficulty target, but has an invalid transaction, the nodes will not recognize this as a valid block. These malicious miners would have occurred both capex and opex to produce valid PoW, however, due to the invalid transaction, they would not receive their pay, earning them a net loss. Miners are thus incentivized to produce valid blocks, and strongly punished if they dare to work on an invalid block. This incentive scheme is important, as Bitcoin requires 51% of miners to be honest.footnote:[Nakamoto, October 2008, Bitcoin: A peer-to-peer electronic cash system]

There have been studiesfootnote:[Marc Bervand, Electricity Consumption of Bitcoin, March 2017 http://blog.zorinaq.com/bitcoin-electricity-consumption/] footnote:[Saad Imran, August 2018, The Positive Externalities of Bitcoin Mining] on the total energy consumption of Bitcoin mining.

Source: [Marc Bevand,footnote:[http://blog.zorinaq.com/bitcoin-electricity-consumption/#fn:elec] Enerdata, Node Blockchainfootnote:[Saad Imran, August 2018 The Positive Externalities of Bitcoin Mining]]

It is evident, that compared to other currency systems, especially a base money, Bitcoin is by far the most energy efficient and cheap alternative.

https://cdn-images-1.medium.com/max/1600/1*CUSPsz71cDIr__-TOR92iw.png

Source: [Dan Hedl]footnote:[Dan Hedl, September 2018, PoW is Efficient https://medium.com/@danhedl/pow-is-efficient-aa3d442754d3]

There are several positive externalities of Bitcoin: (i) efficiency gains in mining hardware; (ii) optimizing power usage effectiveness in data centers; (iii) energy reallocation; (iv) renewable energy; and (v) energy innovation.

(i) Miners are profit seeking entrepreneurs, and thus incentivized to decrease their capex and opex without sacrificing product quality. There have been immense efficiency gains in mining hardware, that is an increase in gigahashes per joule. The market has moved from retail CPUsfootnote:[Central Processing Unit] to GPUsfootnote:[Graphics Processing Unit] to FGPAsfootnote:[Field Programmable Gate Array] and finally to ASICs.footnote:[Aplication-Specific Integrated Circuit] With each upgrade, the number of GH/J has steadily increased, providing more network security for the same level of energy consumed. Koomey’s lawfootnote:[Koomey, Berard, Sanchez, Wong, March 2011, Implications of Historical Trends in the Electrical Efficiency of Computing, Published in: IEEE Annals of the History of Computing ( Volume: 33, Issue: 3, March 2011 )] asserts that the number of computations per joule of energy dissipated doubles approximately every 1.5 years. Since ASICs were introduced in early 2014, their efficiency has increased by 872%, which is a doubling every year, outpacing Koobey’s law.

 

Source: [Node Blockchain Researchfootnote:[Saad Imran, August 2018 The Positive Externalities of Bitcoin Mining]]

(ii) Power usage effectiveness [PUE] measures the ratio between how much energy is used by computing equipment in contrast to cooling and other overhead in a datacenter. The ratio for traditional data centers in Europe have a range of 1.6 to 1.8footnote:[Avgerinou, Bertoldi, Castelazzi September 2017, published in Energies, Trends in Data Center Energy Consumption under the European Code of Conduct for Data Center Energy Efficiency]. Comparatively, Bitcoin mining data centers show a PUE as low as 1.03-1.33footnote:[Bevand, February 2018, Reviewing Morgan Stanley’s Bitcoin Research Reports] This high efficiency is logical given the incentives for miners to allocate as much energy as possible to hashing, and as little as possible to cooling. Clearly, compared to traditional data centers, Bitcoin is not “wasting” energy, but even stating that the countless hours of cat videos hosted on YouTube is a “waste” is a misunderstanding of the subjective nature of value.

“Electricity is generated worldwide in large quantities to satisfy the needs of consumers. The only judgment about whether this electricity has gone to waste or not lies with the consumer who pays for it. People who are willing to pay the cost of the operation of the Bitcoin network for their transactions are effectively financing this electricity consumption, which means the electricity is being produced to satisfy consumer needs and has not been wasted.”footnote:[Ammous, 2017, The Bitcoin Standard, pp.218-219]

(iii) Energy reallocation

 

(iv) Renewable energy

 

(v) Energy innovation.
