The positive externalities of Bitcoin Mining
============================================

One of the major concerns expressed endlessly in mainstream media, is the rather high energy consumption of PoW. The common argument goes, that by now, Bitcoin is using more electricity than [insert your favorite small country here],footnote:[The Economist July 2018 https://www.economist.com/the-economist-explains/2018/07/09/why-bitcoin-uses-so-much-energy]footnote:[CNBC May 2018 https://www.nbcnews.com/tech/tech-news/study-claims-bitcoin-uses-much-energy-ireland-not-so-fast-n875211]footnote:[The Guardian November 2017 https://www.nbcnews.com/tech/tech-news/study-claims-bitcoin-uses-much-energy-ireland-not-so-fast-n875211]footnote:[Forbes, April 2018 https://www.forbes.com/sites/shermanlee/2018/04/19/bitcoins-energy-consumption-can-power-an-entire-country-but-eos-is-trying-to-fix-that/]footnote:[Bitcoin actually uses less electricity than Christmas lights in the US, which is at over 6.63 TWh/yr. https://www.energy.gov/sites/prod/files/maprod/documents/Energy_Savings_Light_Emitting_Diodes_Niche_Lighting_Apps.pdf] and that Bitcoin is even a serious climate threat.footnote:[The Guardian, January 2017 https://www.theguardian.com/technology/2018/jan/17/bitcoin-electricity-usage-huge-climate-cryptocurrency]

PoW is used increase the cost of reordering the transaction history, i.e. double-spending. Once a transaction is propagated by the nodes on the network, miners package several of these transactions from the mempool in an individual candidate block, which also contains a reference to the most recent valid block and a timestamp. A block is only valid, when the SHA256-hash of the block header is below a certain difficulty target. This target is a 256-bit number that is known and verified by all nodes. According to Nakamoto Consensus, the genesis block had a difficulty target of 0x00000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF, this maximum target is the lowest possible difficulty. In order to increase stability and synchronisity, the network strives to keep an average block time of 10 minutes. Every 2016 blocks nodes compare the actual time it took to generate these blocks with the previous two week goal and change the target for the next interval. The target for the following 2016 blocks is modified by the percentage differences: old_difficulty*(2 weeks)/(time the past 2015 blocks took). Thus, if in a 2016 block period the total number of hashes per second has increased, it took less than 20160 minutes to generate the blocks, thus the difficulty target will adjust downwards, increasing the change to find valid PoW. Vice versa, if in a 2016 block period the total hashing power has decreased, it took more than 20160 minutes to generate the blocks, thus the difficulty target will adjust upwards.

Miners have capital expenditure in computer hardware, and operational expenditure in electricity and cooling. Entrepreneurs will only take on expenditures if they  forecast that there is potential profit after selling the produced good to consumers. The good that miners are producing is valid and secure block space. The user pays for inclusion into this block space with every transaction, denominated in Satoshis per virtual Byte.footnote:[BIP141] The more byte a user wants to include in the blockchain, the higher the total fee paid to the miner. Miners usually choose those transaction for their individual candidate block, which pays them the most Satoshis per vByte, maximizing revenue. In addition to the transaction inclusion fee, miners are subsidized by newly created bitcoin, thus they are the ultimate benefactor of the inflationary monetary structure.footnote:[See chapter on Inflation] According to Nakamoto Consensus, a valid block can only have a coinbase transaction with at the most 50 BTCfootnote:[halfing every 210.000 blocks] + the sum of all outputs minus input.footnote:[aggregated transaction fees]

Ultimately, miners receive the coinbase reward if and only if they produce a valid block which does not violate consensus. If they produce a block that is below the difficulty target, but has an invalid transaction, i.e. double spend, the nodes will not recognize this as a valid block. These malicious miners would have been exposed to both capex and opex to produce valid PoW, however, due to the invalid transaction, they would not receive their pay, earning them a net loss. Miners are thus incentivized to produce valid blocks, and strongly punished if they dare to work on an invalid block. This incentive scheme supports the fundamental assumption that 51% of miners are honest.footnote:[Nakamoto, October 2008, Bitcoin: A peer-to-peer electronic cash system]

There are several positive externalities of Bitcoin: (i) efficiency gains in mining hardware; (ii) optimizing power usage effectiveness in data centers; (iii) energy reallocation; (iv) renewable energy; and (v) energy innovation.

(i) Miners are profit seeking entrepreneurs, and thus incentivized to decrease their capex and opex without sacrificing product quality. There have been immense efficiency gains in mining hardware, that is an increase in gigahashes per joule. The market has moved from retail CPUsfootnote:[Central Processing Unit] to GPUsfootnote:[Graphics Processing Unit] to FGPAsfootnote:[Field Programmable Gate Array] and finally to ASICs.footnote:[Aplication-Specific Integrated Circuit] With each upgrade, the number of GH/J has steadily increased, providing more network security at the same level of energy consumed. Koomey’s lawfootnote:[Koomey, Berard, Sanchez, Wong, March 2011, Implications of Historical Trends in the Electrical Efficiency of Computing, Published in: IEEE Annals of the History of Computing ( Volume: 33, Issue: 3, March 2011 )] asserts that the number of computations per joule of energy dissipated doubles approximately every 1.5 years. Since ASICs were introduced in early 2014, their efficiency has increased by 872%, which is a doubling every year, outpacing Koobey’s law.

 

Source: [Node Blockchain Researchfootnote:[Saad Imran, August 2018 The Positive Externalities of Bitcoin Mining]]

(ii) Power usage effectiveness [PUE] measures the ratio between how much energy is used by computing equipment in contrast to cooling and other overhead in a datacenter. The ratio for traditional data centers in Europe have a range of 1.6 to 1.8footnote:[Avgerinou, Bertoldi, Castelazzi September 2017, published in Energies, Trends in Data Center Energy Consumption under the European Code of Conduct for Data Center Energy Efficiency]. Comparatively, Bitcoin mining data centers show a PUE as low as 1.03-1.33footnote:[Bevand, February 2018, Reviewing Morgan Stanley’s Bitcoin Research Reports] This high efficiency is logical given the incentives for miners to allocate as much energy as possible to hashing, and as little as possible to cooling.

(iii) Energy is a homogeneous good, the utility is equal regardless of the location and type of production, however, the prices of electricity varies greatly in different locations. This is partially due to physical limitations, such as storage and transportation of energy is costly; and due to political inefficiencies, that is subsidies and monopoly privileges.footnote:[See chapter on Monopoly] Further, some types of production are more efficient like hydro power, and others are less cost effective, like coal power. In the Yunnan region, a total of 32 billion kWh of hydropower has been wasted due to the government prioritization of other sources of energy production,footnote:[http://www.chinasmartgrid.com.cn/news/20170308/622441.shtml] this is equivalent to the entire annual consumption of Bitcoin mining today. Bitcoin as a digital currency has no physical limitations and entrepreneurs can mine in whatever location they deem effective. Mining hardware, contrary to electricity, can be moved without extraordinary effort, not considering opportunity cost of keeping the hardware offline during transport. Thus, in order to decrease the opex, miners will tend to move to areas of energy overproduction first, as here the cost for electricity should be cheapest. This is basically energy reallocation and arbitrage, as those areas with comparatively cheap production will attract miners away from the inefficient locations. Therefore, PoW mining will improve the overall efficiency in the energy markets, providing a net benefit for society.

Source: BitMEX research group

(iv) As established earlier, miners will tend to utilize the most cost effective energy production available, in some places this is fossil fuel. However, the marginal cost of renewable energy production continues to decline compared to fossil fuels.footnote:[https://ase.tufts.edu/gdae/education_materials/modules/RenewableEnergyEcon.pdf] Miners want to minimize the downtime of the hardware, thus a continuous stream of electricity is preferable. Energy sources like hydro and nuclear are ideal due to their inherent stable and renewable nature, opposed to the sporadic production of solar and wind. According to the BitFury board director Bill Tai,footnote:[Venture Stories, August 2018, Crypto Stories: Bill Tai and Derek Hsue on Mining, Exchanges and the History and Future of Money] Bitfury has long been mining solely with renewable energy sources, and he is advocating other miners to do the same. Miners will first take advantage of misallocated energy surpluses, and once these sources have been used up, invest in renewable energy sources to further decrease marginal costs.

(v) Due to the inherent free market and open source philosophy of Bitcoin, there are countless entrepreneurs innovating without permission. Energy innovation is not an exception to this, because of this competitive market, advancements and improvements of old technology is needed and very profitable. Steven Barbour has built the first plug-and-play waste-to-energy crypto miner,footnote:[Pompliano, November 2017, The World’s First Waste-To-Energy Crypto Miner] which utilizes otherwise wasted natural gas.footnote:[Chandler, MIT News Office, October 2017 A new way to harness wasted methane] This is only one innovation of many to come which will further increase global energy production and efficiency. Soon space entrepreneurs will build dyson spheresfootnote:[suggested by Peter Todd] to harness the direct power of the sun to secure the Bitcoin network.

There have been studiesfootnote:[Marc Bervand, Electricity Consumption of Bitcoin, March 2017 http://blog.zorinaq.com/bitcoin-electricity-consumption/] footnote:[Saad Imran, August 2018, The Positive Externalities of Bitcoin Mining] on the total energy consumption of Bitcoin mining.

.Bitcoin Mining Energy Consumption; Source: [Marc Bevand,footnote:[http://blog.zorinaq.com/bitcoin-electricity-consumption/#fn:elec] Enerdata, Node Blockchainfootnote:[Saad Imran, August 2018 The Positive Externalities of Bitcoin Mining]]
[cols="h,4*",options="header",width="50%"]
|=================================================================================
|      |Lower bound |Estimate |Upper bound |
|Power Consumption (MW)    |2,269  |3,115     |3,960 |  
|Energy Consumption (TWh/yr)    |19.90  |27.31     |34.73 |  
|Percentage of world's energy consumption    |0.0121%  |0.0166%     |0.0211%  |
|Percentage of world's electricity consumption    |0.0904%  |0.1241%     |0.1577%  |
|Energy Efficiency (J/GH)    |0.057  |0.079     |0.1  |
|Electricity cost (million USD/yr)    |USD 995  |USD 1,366     |USD 1,736  |
|Global Hashrate (TH/s)    |39,602  |     |  |
|=================================================================================

It is evident, that compared to other currency systems, especially a base money, Bitcoin is by far the most energy efficient and cheap alternative.

.Comparison Energy Cost of Moneys; Source: [Dan Hedl]footnote:[Dan Hedl, September 2018, PoW is Efficient https://medium.com/@danhedl/pow-is-efficient-aa3d442754d3]
[cols="h,3*",options="header",width="50%"]
|=================================================================================
|      |Yearly Cost in Billion USD|Energy Used in Million GJ |
|Gold Mining    |105  |475     |
|Gold Recycling    |40  |25     |
|Paper Currency and Minting    |28  |39     |
|Banking System    |1,870  |2,340     |
|Governments    |27,600 |5,861 |
|Bitcoin Mining    |4.5  |183     |
|=================================================================================


Clearly, compared to traditional data centers and other types of money, Bitcoin is not “wasting” energy. Even stating that the countless hours of cat videos hosted on YouTube is a “waste” is a misunderstanding of the subjective nature of value.

“Electricity is generated worldwide in large quantities to satisfy the needs of consumers. The only judgment about whether this electricity has gone to waste or not lies with the consumer who pays for it. People who are willing to pay the cost of the operation of the Bitcoin network for their transactions are effectively financing this electricity consumption, which means the electricity is being produced to satisfy consumer needs and has not been wasted.”footnote:[Ammous, 2017, The Bitcoin Standard, pp.218-219]

 

In conclusion, the FUD regarding Bitcoins electricity consumption is neither based on reason nor logic. The incentive to produce electricity as productive and resourceful as possible so to increase mining profitability is an immense push towards efficient renewable energy sources that will not just be used for mining. Further, compared to conventional data centers, Bitcoin mining farms are far more efficient already and this tendency will probably further develop. All this consumed energy goes directly into securing the blockchain against reorganizations and double spends, thus the more energy is consumed, the better. The increase in overall hashing power will likely continue, until a point is reached where network security is adequate for the economic value secured in the Bitcoin blockchain, depending on individual valuation, this might be as high as 50% of global energy consumption, as money is used in half of every economic transaction. Bitcoin mining is pushing the limits of innovation and advancement in both energy production and efficient energy allocation, this will usher in an unprecedented of area of prosperity and delightfulness.
