On scarce and non-scarce goods
==============================

There are two different type of goods, scarce and non-scarce. If taking the original good eliminates the possession of the previous owner, it is a scarce good; but if a good can be taken without displacing the original, it is non-scarce. Most goods however, are a combination of both types.

A 3D tangible good is scarce, there can be conflict over who has the right to own and use such good. The very possibility of such a conflict make ethical rules over who controls that good necessary. Property rights are the fundamental tool to organize such scarce goods and prevent never-ending conflict over the resources. Hoppe writes: “only because scarcity exists is there even a problem of formulating moral laws; insofar as goods are superabundant (‘free’ goods), no conflict over the use of goods is possible and no action-coordination is needed”.footnote:[Hoppe, Theory of Socialism and Capitalism, p.158, n.120.] Property is a concept or a mutually binding rule that enables conflict-free interaction in a scarce world. At the minimum, there exists scarcity in the body and time of humankind, even in a hypothetical construct of superabundance.footnote:[Hoppe, Theory of Socialism and Capitalism, p.20-21] Property right in body and time are thus the precondition for all human action. Only the true ‘owner’ of the body can by sheer power of will directly coordinate and manage it, for example lifting the arm after explicitly expressing the desire. Another person can only indirectly move and modify the body of the first, they need to employ their own body in order to move the other, i.e. physically touching the other persons arm and lifting it up with their own.

Scarcity does not automatically create a price of the good, as that also presupposes demand for such a good. A mud pie is by definition scarce, there can be conflict over who owns and controls it, but most likely, it will not have a price in the market. Nor does scarcity refer to the quantity available of the good, or the rarity of it. There can be a single owner of a non-scarce good, for example the creator of a poem that is not yet public, i.e. it is still in the mind of the poet. But also billions of scarce goods, which are controlled by billions of owners such as pieces of paper. Neither does scarcity only apply to tangible goods that can be interacted and sensed in the 3D world. Airspace or radio airwaves are intangible scarce goods, where conflict can arise over who has the right to use them.

Scarcity is thus defined by the possibility of arising conflict over the true owner and manager of a finite thing. It applies to anything and everything that cannot be simultaneously owned, i.e. one’s ownership and control excludes others. Scarce goods can only be acquired either by the homesteading unused resources, by the economic mean, i.e. trading in a voluntary market, or by the political mean, i.e. forcefully taking the good from an unwilling subject. Scarce goods are allocated and rationed by prices in the free market.

On the other hand are non-scarce goods, which due to their super-abundance are not subject to desire and choice. Those free goods don’t have value in the classical sense, but they exist in superfluity, they gratify and also satisfy all desires which depend on them.footnote:[Frank Fetter, Economic Principles, Chapter 1, §3] It is thus a nonfinite good, which can be replicated without limit, so that everybody can satisfy his desire for it and there is no conflict over ownership. No additional copy will replace the previous copies, nor degrade the quality of the copied good.

Ideas can be kept exclusively by the owner as long as he keeps it to himself, but as soon as he utters the thoughts, they force themselves into the possession of everyone that heard the words. The peculiar attribute is that the original thinker still holds full possession over his idea, and all others receive the full expression without any loss. Similar to a match that can light another, without becoming extinct by the passing on the flame. This is a benevolent design of nature, that ideas can be shared freely and openly without lessening the quality, and at no costs to the original thinker.footnote:[Thomas Jefferson to Isaac McPherson, Aug. 13, 1813, Writings 13, pp. 333-335] When speaking words, they can be taken all to oneself, yet leave all to others and unless the memory fades away, everyone who can hear those words, can take them all and go on each separate way.footnote:[St. Augustine, Garry Wills, Viking 1999, p. 145]

If this were true for finite things, let’s say a loaf of bread, one could give away the bread and another exact copy would appear in its stead. The very act of giving it away, would create a copy. With such a replicable loaf of bread, a free good, a non-scarce good, there will never be conflict of ownership, as anyone in need can receive the bread without taking it away from someone else.

This sounds nonsensical in the example of a loaf of bread, but the same concept does apply to many goods today. With the advent of the printing press, a sheer limitless number of book could be copied without losing any quality in content and without destroying the original book. With new technologies today such as laser printers and 3D printers, we can manufacture various tangible objects by using a “recipe”. The same is true for a song, which anyone can sing after it is initially performed. The concept further applies to all digital information, for example a pdf document, mp3 music files or jpeg picture can be copied perfectly ad infinitum for near zero cost. In general, the World Wide Web is an interconnected network of nodes copying and sharing non-scarce goods, sending them to anyone who is interested in receiving them. As we continue moving towards a digital world, the number of non-scarce goods will continue to increase drastically. There is no conflict of ownership and control, and thus no property rights apply in this cyberspace.

Property rights are essential for scarce goods, as they are the basis of all human action. There is no “social ownership” in scarce goods, because at any time, only one single owner exists. Sharing the scarce good only temporarily transfers ownership and control to another person, and does not alter the intrinsic nature of scarce goods. Prices arise in scarce goods to ration the unique goods and allocate them to the most urgent need. Because free goods are only guides for human action and can be copied to satisfy each and every desire, there are no property rights and no need to economize and ration them based on price. “Action is purposive conduct. It is not simply behavior, but behavior begot by judgments of value, aiming at a definite end and guided by ideas concerning the suitability or unsuitability of definite means.”footnote:[Ultimate Foundation of Economic Science, p. 34] Although there is no structure of production when sharing non-scarce goods, they can be economized and commercialized. For example, a teachers time and body is limited and scarce, thus his payment is not for the sharing of non-scarce ideas, but for the presentation and his labor service, which is of course a scarce good.footnote:[Kinsella, A Libertarian Theory of Contract: Title Transfer, Binding Promises, and Inalienability”, Journal of Libertarian Studies 17, no.2, pp. 24-26] Same applies for books, as the ideas conveyed by the content can be copied and are thus non-scarce, but the paper and ink themselves are the unique and scarce medium over which the information is transferred.

Non-scarce goods are all kinds of thoughts, ideas, art, and all other information and therefore essential to everyday life. Without these free gifts, there would be no innovation, learning nor advancement. Society can only progress through imitation of accumulated knowledge. Entrepreneurs emulate the success of others and gather experience also from failings. Profits incentivize new entrepreneurs to copy the successful business model and adapt it to their unique circumstances. Non-scarce goods are thus the driver of all competitive business. “These designs – the recipes, the formulas, the ideologies – are the primary thing; they transform the original factors – both human and nonhuman – into means.footnote:[Mises, Human Action, p. 142] Once the idea is “produced” it no longer has to be produced, it is an unlimited factor of production. Ideas themselves don’t create wealth, but rather the action that arises out of the initial thought.


Now that we have established that ideas are non-scarce goods and should therefore be shared openly with anyone, let us consider government enforced intellectual property rights. The name itself already contains a fallacy, as only scarce goods give rise to property rights, in order to organize and allocate resources. Because ideas are non-scarce, there are no property rights necessary to ration the good, it can be shared endlessly at almost no cost to the “original” thinker. Rather, sharing an idea and propagating it throughout society increases the value of the idea, as more people know about it, can understand it and eventually act upon them accordingly.footnote:[McLuhan, The Classical Trivium] Only when the thought is shared can it outlive the “original” thinker.

With intellectual property rights, not the “original” thinker, but the person that first registers the idea at a government institution, receives the monopoly right to “use” this idea. Only he has the legal “right” to manifest the thought into reality. If anyone else dares to act upon this idea, the patent holder is supported by government thugs in aggressively stopping or hindering that manifestation. This also applies, even though another person might come up with the idea independently and without any knowledge of the previous thinker. If this person, who possesses the rightful property in the original factors, with the application of the idea turns them into means, the patentee is supported in violating the property rights and confiscating or destroying the property or otherwise extracting wealth from the second thinker.

Intellectual property rights thus break the fundamental nature of non-scarce goods and tries to introduce artificial scarcity where none exists. A good that can be gifted freely and openly to anyone, is limited without any need to do so, nobody is stolen from when sharing an idea. Furthermore, the person that apparently “stole” the idea, is violated in his property rights and liberty. Thugs literally steal his property on the basis, that some other person had a thought before him. This regulation not only hinders the general advancement of society, through the artificial scarcity of a free and limitless good, but further breaks the Natural Law inherent in creation. Intellectual Property is thus neither economically sound, nor morally righteous.


Early cypherpunk’s realized the economic and moral fallacies of intellectual property, and saw the immense potential of creating a community in cyberspace where free non-scarce goods can be shared as open and as widely as possible. A fundamental building block of today’s Internet is the realization, that code is non-scarce speech and therefore protected by the Natural Law of freedom of speech and expression. This especially applies to privacy enhancing technologies such as encryption.

The natural conclusion of this realization is, that the code of each and every application should be open source, that it is shared and that anyone can see and edit the source code of the software. Only this way can the sheer limitless potential of non-scarce goods be reached. Once the code is written, it can be shared at no cost to the creator. It is evident, that there is no perfect and bug-free code. Thus the more developers take a look at the code and check for validity and security, the more the refined the code will be. Permissionless innovation means, that anyone can work on any problem and try to solve it. Nobody has to ask for permission in order to fix or break something, just like nobody has to ask for permission to write a poem or sing a song. This creates countless black swan events, where a seemingly unsolvable problem is solved in an unexpected but brilliant approach. Nobody thought about this, but one person somewhere on the interwebs did. As soon as this hidden genius shares his solution to the problem, he has unleashed the power of the non-scarce idea and everybody can copy, adapt and improve the approach. Only one person in a billion needs to find the solution, if he freely shares it with the world, everybody will benefit. Therefore, free software will always outperform any guarded and closed source software: open software wins.footnote:[Rosenberg, The meaning of open, https://googleblog.blogspot.com/2009/12/meaning-of-open.html]

Further, the software user should have full control and trust in the hard- and software that he is running. In a closed source system, there is no possibility of the user to check if the software is doing, what it is advertised to do. He has to blindly trust the intransparent developers. Contrarily, in an open source system the user can, if he has the ability, verify for himself, what the code is and if the software is running secure and sound. Even if the user himself does not have the ability to verify the codes validity, he can verify if there are developers working on improvements and bug fixes. If those developers are reputable and the user can trust their skill and dedication, he has a much higher insurance that the code is clean. Don’t trust ~ verify.



In the incumbent financial system, only a hand full of people and organizations, if any, have the power to verify the inner workings of the money economy. Central banks pride themselves in being intransparent and to use convoluted vapor speech to confuse the layman. Meetings are held in private and the transcript is usually not available for the public. Each week the monetary policy is decided only by the small counsel with no public input and feedback. Furthermore, the US FED holds countless patents, which of course hinder innovation in the money economy.footnote:[https://patents.justia.com/search?q=federal+reserve+bank] Even worse, the US FED has never been publicly audited, it is thus a very intransparent black box and nobody really knows what’s happening. To summarize, central banks are everything but open and accessible.

Bitcoin, on the contrary, is entirely and relentlessly open source. Each and every line of code is auditable. Several thousand volunteers work on the code in an equal and transparent process. Everybody can fork the code, make changes and issue a pull request to merge the code. However, this does not mean that anyone can easily change the code of the bitcoin core client, or even the protocol rules. There is a rigorous peer review processfootnote:[Bitcoin Improvement Proposal] where even the most trivial of changes gets audited by several different developers, nobody trusts anyone.

Bitcoin spawns out of the internet of open source non-scarce goods, a protocol on the network. The software running the consensus code is fully transparent and auditable buy every single full node. It can be downloaded and installed on any scarce hardware that the the individual owns. 
Bitcoin is entirely and relentlessly open source. Each and every line of code is auditable, several thousand volunteers work on the code in an equal and transparent process. Everybody can fork the code, make changes and issue a pull request to merge the code without permission. However, this does not mean that anyone can easily change the code of the bitcoin core client, or even the change the protocol rules of a sovereign node. There is a rigorous peer review processfootnote:[Bitcoin Improvement Proposal] where even the most trivial of changes gets audited by several different developers, nobody trusts anyone. Because of the open source code, and the general attitude of don’t trust ~ verify of Bitcoin, the user has full control over which software they deploy on their own hardware.

A private key is only a large random number, a piece of information that is non-scarce and can be copied endlessly, without any cost and at no loss to anyone. However, in the Bitcoin script corresponding to a UTXO can be the requirement to prove control over this private key with an elliptic curve digital signature. Thus, only with knowledge of the private key, can the bitcoin be spent. Other bitcoin script programs can assign the claim to the bitcoin, to anyone who can fulfill all the conditions, like proof of knowledge of several private keys with a multi signature, or a time delay in check sequence verify. Further advanced smart contracts such as the lightning network can shift the state of a MultiSig off chain. All these scripts provide a clear set of rules over who has access and the right to control these specific bitcoin. With the brilliant pattern of speech, nakamoto consensus emerges cryptographically proven scarcity. 

In order to secure this attribute of scarcity, Bitcoin employs a plethora of economic incentives and applies monetary theory. In order to secure Bitcoin against a double spend, the duplication of one UTXO, miners order and timestamp transaction and accumulate cryptographic proof of work. Because miners gain economic financial gains and profits with scarce bitcoin in the coinbase reward, they are incentivized to adhering to consensus rules. With a majority of miners accepting consensus as defined by individual sovereign nodes, the chain with the most accumulated PoW contains the valid time order of transactions. PoW is needed to defend bitcoins scarcity even against malicious actors trying to use the same UTXO twice. Running a node and accumulating valid PoW is a tool for defending the Nakamoto consensus which upholds the attribute of scarcity of bitcoin.
