Sidechains
==========

Sidechainsfootnote:[Enabling Blockchain Innovations with Pegged Sidechains, Back, Corallo, Dashjr,
Friedenbach, Maxwell, Miller, Poelstra, Timón, and Wuille, 2014] are another scaling proposal, which leverages the security and trustlessness of the parent chain, Bitcoin. An entirely new data structure managing digital assets can be interlocked to the PC, in such a way that the SC tokens are pegged to the PC token. This data structure can be a blockchain,footnote:[for example Elements https://elementsproject.org/] but also hash graphs or state machines are possible. This separate protocol can change and introduce new rules, that would break the PC consensus, but these are agreed to voluntarily through the opt in individual action.

In order to create SC tokens, PC bitcoin are send to a m of n multisig wallet, that is controlled by a known and non-dynamic federationfootnote:[Strong Federations: An Interoperable Blockchain Solution to Centralized Third Party Risks, Dilley, Poelstra, Wilkins, Piekarska, Gorlick, and Friedenbach] of n semi-trusted individuals. Anyone can send funds into this wallet, but only with m signatures can they be released again. With a simple payment verificationfootnote:[Nakamoto 08 Simple Payment Verification] prooffootnote:[Proofs of Proofs of Work with Sublinear Complexity, Kiayias, Lamprou, and Stouka] Alice can proof that she’s send the funds and that they are confirmed by sufficient accumulated PoW. With this proof, the SC tokens are created and issued by the federation. Once it is issued, it is linked to the corresponding key pair of Alice, and she can transfer the coin according to SC consensus. Now Alice can utilize the additional use cases of the SC which are not possible on the PC, for example in the case of Liquid,footnote:[https://github.com/Blockstream/liquid] confidential transactions,footnote:[refer to Greg Maxwell's original investigation https://elementsproject.org/features/confidential-transactions/investigation] confidential assets,footnote:[refer to Andrew Poelstra's original investigation https://elementsproject.org/features/issued-assets/investigation] additional op codes,footnote:[such as OP_DETERMINISTICRANDOM https://github.com/ElementsProject/elements/search?q=deterministicrandom&unscoped_q=deterministicrandom and OP_CHECKSIGFROMSTAG https://github.com/ElementsProject/elements/search?q=CHECKSIGFROMSTACK&unscoped_q=CHECKSIGFROMSTACK] and 2 minute final settlement. Alice and Bob can exchange PC bitcoin with SC token through cross chain atomic swaps,footnote:[Connor Fromknecht, Connecting Blockchains: Instant Cross-Chain Transactions On Lightning https://blog.lightning.engineering/announcement/2017/11/16/ln-swap.html] without issuing or destroying any SC token. Alice can at any time destroy the SC token by sending it to OP_RETURNfootnote:[BIP 0074, Padilla, https://github.com/bitcoin/bips/blob/master/bip-0074.mediawiki], and add her PC Bitcoin address. With this burning transactions, the federation members, specifically the watchmen functionaries, shall release the PC bitcoin out of the n of m multi signature wallet. Although Alice does not need any additional communication other than the SC burning transaction, she needs to trust the federation to initiate the release transaction.

Because on the SC any consensus can be change, and new features and trust models are introduced, the SC token is not the same asset as the PC bitcoin. Just like one liter of water in the Sahara is not equal to one liter of water close to a fountain. However, it can be cryptographically set, that one SC token can only be issued when PC bitcoin are locked in multi sig, and that the PC bitcoin are released only when the SC token is burned. Thus, the SC token can be backed by PC bitcoin, and this peg will be enforced and uphold by individuals creating and destroying SC token according to SC consensus. However, because Alice and Bob can exchange these two tokens independently and without utilizing the two way federated peg, there might be a swap market price independent and different to the 1 to 1 peg.footnote:[refer to the elements how it works https://elementsproject.org/how-it-works#federatedpeg] Any price discrepancy will be arbitraged by individuals who create or destroy SC tokens and swap between the two chains.

Thus, a SC token is a separate digital asset, registered in a separate data structure, adhering to separate consensus rules. However, due to the federated two way peg, at any time can the SC token be liquidated to PC bitcoin, according to the specified 1 to 1 peg. Further, Alice and Bob can independently exchange these two assets at their own desired exchange rate. Arbitrageurs will likely uphold the 1 to 1 peg even for the exchange rate of the atomic swaps. The SC is not as trustless as the PC, because a hyper majority of the federation could steal the PC bitcoin locked up in multi sig, however, this trade off might be justified for individuals who seek to participate in the changed consensus and use the added functionalities. Especially for activities of exchanges, who are usually the sole trusted custodian of the funds, this trade-off is justified. The SC token is not an altcoin, or new crypto currency, as it is created solely by the reserving of PC bitcoin, and uphold by a 1 to 1 peg. However, as SC allow for limitless permissionless innovation, there might be SC which would count as an altcoin without a 1 to 1 peg.
