Why to Run a Full Node
======================

Bitcoin is an electronic peer-to-peer cash system.footnote:[Satoshi Nakamoto 2008, Bitcoin Whitepaper] The important aspect is peer-to-peer, that is that the individual user has full control over the system, and doesn't delegate the power to a centralized party. However, the system is truly trust less, if and only if the individual user runs a full node. This is a piece of software that can be installed on any hardware, [computer, laptop, RaspberryPi,footnote:[Tutorial to install Bitcoin Core on a RaspberryPi available at http://www.raspberrypifullnode.com/] smartphonefootnote:[ABCore by Blockstream] etc.] and by anyone who wants to. UltimatelyUltimately, the end user could write this software from scratch, but this is of course very complex and not reasonable to assume. There are several different clients already, that can be used in order to communicate with the rest of the network, the most advanced of these software is the Bitcoin Core client.footnote:[Bitcoin Core Client, latest version available at https://github.com/bitcoin/bitcoin] It is 100% open source, each and every line code can be seen, copied, changed and improved by anyone, without asking for permission, thus everyone can verify the entire software.

When downloading the Bitcoin clients, Alice can set any kind of individual rule that she wants. She could increase the number of Bitcoin in existence, change the proof-of-work algorithm, change the network routing, or take away control from another UTXO and give herself the control over these coins. There are literally no restrictions on the individual user, he can change anything and everything he wants. 

When downloading one of the Bitcoin clients, the individual user can thus verify everything in the software, and can change any parameter. The user can set any kind of consensus rule that he wants. He could increase the number of Bitcoin in existence, change the proof-of-work algorithm, change the network routing, or take away control from another UTXO and give himself the control over this UTXO. There are literally no restrictions on the individual user, he can change anything and everything he wants. Of course, as soon as one person changes some of the rules, he might violate the rules of all the other individual nodes, those will recognize him as an aggressor against their individual rules. Because money is a network good, it increases its value exponentially with any additional participants. As soon as someone has different rules in the system, he is excluded from the network. The users with the minority rule change, thus diminish the value of their money drastically. Therefore, there is a natural incentive for the individual, to use the same rules in his money as the majority of the economy does. Regardless, the individual user has full control over which rules he wants to comply with, and there is no coercion whatsoever. By definition, anyone who runs a full node thus voluntarily agrees to the rules of the network, nobody is forced to use this software as is.

Not only does the individual user set his own consensus rules, he also verifies each and every single transaction that occurs on this network. If an incoming transaction complies with all the rules the individual set, he will accept the transaction. However, if another node propagates a transaction which the individual node deems wrong, he can and will ignore this transaction and possibly block the node that sent it. A user with a full node neither has to trust that someone is verifying if the rules are complied with, nor does he have to trust anyone to enforce the rules for him, he does this by himself without anyone's permission.

A user who runs a full node thus chooses which rules he likes, verifies if they are uphold, and if not, punishes the nodes that don't comply. He thus is the judge, jury and executioner. He is the king of his money, the sovereign of his money. And nobody can take this away from him.

This is why Bitcoin is unique and so innovative. Anyone and everyone has 100% ownership and control over his money, nobody can force him to do anything. This is further why closed source and permissions blockchain projects are simply boring and not innovative. They retain the control by the trusted centralized party and don't give the power to the user. It's the intranet, filled with stale, boring and old content; to the internet, a network of freedom, ideas and without any censorship.
